DataModel/main/default/objects/Recommended_Badge__c/Recommended_Badge__c.object-meta.xml
<CustomObject>
    <label>Recommended Badge</label>
    <nameField>
        <displayFormat>RB-{0000000}</displayFormat>
        <label>Recommended Badge Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Recommended Badges</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Core/objects/Recommended_Badge__c/fields/BadgeAPIName__c.field-meta.xml
<CustomField>
    <fullName>BadgeAPIName__c</fullName>
    <label>Badge API Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

DataModel/main/default/objects/Recommended_Trail__c/Recommended_Trail__c.object-meta.xml
<CustomObject>
    <label>Recommended Trail</label>
    <nameField>
        <displayFormat>RT-{0000000}</displayFormat>
        <label>Recommended Trail Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Recommended Trails</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Core/objects/Recommended_Trail__c/fields/TrailAPIName__c.field-meta.xml
<CustomField>
    <fullName>TrailAPIName__c</fullName>
    <description>Value of the trailheadapp__API_Name__c field on the corresponding trailheadapp__Trail__c record.</description>
    <label>Trail API Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

Core/objects/TrailTrackerProviderFieldMapping__mdt/TrailTrackerProviderFieldMapping__mdt.object-meta.xml
<CustomObject>
    <description>Custom metadata type to hold mappings of fields custom objects to fields on objects in the Trail Tracker Provider org.</description>
    <label>Trail Tracker Provider Field Mapping</label>
    <pluralLabel>Trail Tracker Provider Field Mappings</pluralLabel>
</CustomObject>

Core/objects/TrailTrackerProviderFieldMapping__mdt/fields/ProviderField__c.field-meta.xml
<CustomField>
    <fullName>ProviderField__c</fullName>
    <description>API name of the tracked field in the Trail Tracker Provider org.</description>
    <label>Provider Field</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

Triggers/objects/TrailTrackerProviderFieldMapping__mdt/fields/RecommendedBadgesField__c.field-meta.xml
<CustomField>
    <fullName>RecommendedBadgesField__c</fullName>
    <description>API name of the mapped field in the Recommended Badges org.</description>
    <label>Recommended Badges Field</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

Core/objects/TrailTrackerProviderFieldMapping__mdt/fields/TrailTrackerProviderObjectMapping__c.field-meta.xml
<CustomField>
    <fullName>TrailTrackerProviderObjectMapping__c</fullName>
    <description>Custom object mapping to object in the Trail Tracker Provider org.</description>
    <label>Trail Tracker Provider Object Mapping</label>
    <referenceTo>TrailTrackerProviderObjectMapping__mdt</referenceTo>
    <relationshipName>TrailTrackerProviderMappings</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

Core/objects/TrailTrackerProviderObjectMapping__mdt/TrailTrackerProviderObjectMapping__mdt.object-meta.xml
<CustomObject>
    <description>Custom metadata type to hold mappings of custom objects to objects in the Trail Tracker Provider org.</description>
    <label>Trail Tracker Provider Object Mapping</label>
    <pluralLabel>Trail Tracker Provider Object Mappings</pluralLabel>
</CustomObject>

Core/objects/TrailTrackerProviderObjectMapping__mdt/fields/RecommendedBadgesObject__c.field-meta.xml
<CustomField>
    <fullName>RecommendedBadgesObject__c</fullName>
    <description>Mapped object in the Recommended Badges org.</description>
    <label>Recommended Badges Object</label>
    <referenceTo>EntityDefinition</referenceTo>
    <relationshipLabel>TrailTrackerProviderObjectMappings</relationshipLabel>
    <relationshipName>TrailTrackerProviderObjectMappings</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

Triggers/classes/QueueableTrailTrackerProviderCallout.cls
/**
 * Queueable Apex job to make callouts to Trail Tracker Provider org to retrieve values for new Recommended Badge/Recommended Trail records from the corresponding fields on 
 * the related Badge/Trail records.
 * @author Ben Learn
 * @since 06-10-2024
 */
public with sharing class QueueableTrailTrackerProviderCallout implements Queueable, Database.AllowsCallouts {
    private final Id RECORD_ID;
    private final String SOBJECT_API_NAME;
    private final Map<String, String> PROVIDER_SOBJECTS_BY_OBJECT_API_NAME {
        get {
            if(this.PROVIDER_SOBJECTS_BY_OBJECT_API_NAME == null) {
                this.PROVIDER_SOBJECTS_BY_OBJECT_API_NAME = new Map<String, String>();
                List<TrailTrackerProviderObjectMapping__mdt> objectMappings = [
                    SELECT MasterLabel, RecommendedBadgesObject__r.QualifiedAPIName
                    FROM TrailTrackerProviderObjectMapping__mdt
                ];
                for(TrailTrackerProviderObjectMapping__mdt objectMapping : objectMappings) {
                    this.PROVIDER_SOBJECTS_BY_OBJECT_API_NAME.put(objectMapping.RecommendedBadgesObject__r.QualifiedAPIName, objectMapping.MasterLabel);
                }
            }
            return this.PROVIDER_SOBJECTS_BY_OBJECT_API_NAME;
        }
        set;
    }

    private final Map<String, String> PROVIDER_TO_RECOMMENDED_BADGES_FIELD_MAP {
        get {
            if(this.PROVIDER_TO_RECOMMENDED_BADGES_FIELD_MAP == null) {
                this.PROVIDER_TO_RECOMMENDED_BADGES_FIELD_MAP = new Map<String, String>();
                List<TrailTrackerProviderFieldMapping__mdt> fieldMappings = [
                    SELECT RecommendedBadgesField__c, ProviderField__c
                    FROM TrailTrackerProviderFieldMapping__mdt
                    WHERE 
                        TrailTrackerProviderObjectMapping__r.RecommendedBadgesObject__r.QualifiedApiName = :this.SOBJECT_API_NAME 
                        AND TrailTrackerProviderObjectMapping__r.MasterLabel = :this.PROVIDER_SOBJECTS_BY_OBJECT_API_NAME.get(this.SOBJECT_API_NAME)
                ];
                for(TrailTrackerProviderFieldMapping__mdt fieldMapping : fieldMappings) {
                    this.PROVIDER_TO_RECOMMENDED_BADGES_FIELD_MAP.put(fieldMapping.ProviderField__c, fieldMapping.RecommendedBadgesField__c);
                }
            }
            return this.PROVIDER_TO_RECOMMENDED_BADGES_FIELD_MAP;
        }
        set;
    }

    private String entityAPIName {
        get {
            if(this.entityAPIName == null) {
                switch on this.SOBJECT_API_NAME {
                    when 'Recommended_Badge__c' {
                        this.entityApiName = new RecommendedBadgesSelector().selectBadgeAPINameById(this.RECORD_ID).BadgeAPIName__c;
                    } when 'Recommended_Trail__c' {
                        this.entityApiName = new RecommendedTrailsSelector().selectTrailAPINameById(this.RECORD_ID).TrailAPIName__c;
                    }
                }
            }
            return this.entityApiName;
        } 
        set;
    }

    /**
     * Constructor to take record Id of new Recommended Badge/Trail and initialize instance variables.
     * @param recordId 
     */    
    public QueueableTrailTrackerProviderCallout(Id recordId) {
        this.RECORD_ID = recordId;
        this.SOBJECT_API_NAME = recordId.getSobjectType().getDescribe().getName();
    }

    /**
     * Makes REST API callout to Trail Tracker Provider org to get values of mapped fields on corresponding Badge/Trail record, then updates specified 
     * Recommended Badge/Recommended Trail with results.
     * @param context 
     */    
    public void execute(QueueableContext context) {
        String query = String.format(
            'SELECT Id, {0} FROM {1} WHERE trailheadapp__API_Name__c = \'' + this.entityAPIName + '\'',
            new List<Object>{
                String.join(new List<String>(PROVIDER_TO_RECOMMENDED_BADGES_FIELD_MAP.keySet()), ', '),
                this.PROVIDER_SOBJECTS_BY_OBJECT_API_NAME.get(this.SOBJECT_API_NAME)
            }
        );

        sObject recordToUpdate = this.RECORD_ID.getSObjectType().newSObject(this.RECORD_ID);
        HttpRequest request = new HttpRequest();
        request.setEndpoint('callout:Provider_Scratch/services/data/v60.0/query/?q=' + EncodingUtil.urlEncode(query, 'UTF-8'));
        request.setMethod('GET');
        HttpResponse response;

        try {
            response = new Http().send(request);
        } catch(Exception e) {
            Logger.error(new LogMessage('Error with callout to Trail Tracker Provider. {0}: {1}. \n{2}', e.getTypeName(), e.getMessage(), e.getStackTraceString()));
            Logger.saveLog();
            return;
        }

        if(response.getStatusCode() == 200) {
            Map<String, Object> record = getRecordFromResponseBody(response.getBody());
            Set<String> providerFields = PROVIDER_TO_RECOMMENDED_BADGES_FIELD_MAP.keySet();
            for(String field : record.keySet()) {
                if((field != 'attributes') && providerFields.contains(field) && (field != 'trailheadapp__API_Name__c')) {
                    recordToUpdate.put(this.PROVIDER_TO_RECOMMENDED_BADGES_FIELD_MAP.get(field), record.get(field));
                }
            }
        } else {
            Logger.error(new LogMessage('Error with callout to Trail Tracker Provider. {0}. {1}', response.toString(), response.getBody()));
            Logger.saveLog();
            return;
        }

        try {
            update recordToUpdate;
        } catch(Exception e) {
            Logger.error(new LogMessage('Error updating {0}. {1}: {2}. \n{3}', new List<String>{this.SOBJECT_API_NAME, e.getTypeName(), e.getMessage(), e.getStackTraceString()}));
            Logger.saveLog();
        }
    }

    private Map<String, Object> getRecordFromResponseBody(String responseBody) {
        return (Map<String, Object>) ((List<Object>) ((Map<String, Object>) JSON.deserializeUntyped(responseBody)).get('records'))[0];
    }
}