DataModel/main/default/objects/Recommended_Badge__c/Recommended_Badge__c.object-meta.xml
<CustomObject>
    <label>Recommended Badge</label>
    <nameField>
        <displayFormat>RB-{0000000}</displayFormat>
        <label>Recommended Badge Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Recommended Badges</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Recommended_Badge__c/fields/Badge__c.field-meta.xml
<CustomField>
    <fullName>Badge__c</fullName>
    <label>Badge</label>
    <referenceTo>trailheadapp__Badge__c</referenceTo>
    <relationshipLabel>Recommended Badges</relationshipLabel>
    <relationshipName>Recommended_Badges</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Recommended_Badge__c/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <label>Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Level</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Recommended_Badge__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Module</fullName>
                <default>true</default>
                <label>Module</label>
            </value>
            <value>
                <fullName>Project</fullName>
            </value>
            <value>
                <fullName>Superbadge</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

DataModel/main/default/objects/Recommended_Trail__c/Recommended_Trail__c.object-meta.xml
<CustomObject>
    <label>Recommended Trail</label>
    <nameField>
        <displayFormat>RT-{0000000}</displayFormat>
        <label>Recommended Trail Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Recommended Trails</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Core/objects/Recommended_Trail__c/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <description>Value of the trailheadapp__Level__c field on corresponding trailheadapp__Trail__c.</description>
    <label>Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Level</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Recommended_Trail__c/fields/Trail__c.field-meta.xml
<CustomField>
    <fullName>Trail__c</fullName>
    <label>Trail</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Only active trails can be added to a mix.</errorMessage>
        <filterItems>
            <field>trailheadapp__Trail__c.trailheadapp__Archived__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>trailheadapp__Trail__c</referenceTo>
    <relationshipLabel>Recommended Trails</relationshipLabel>
    <relationshipName>Recommended_Trails</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackageable/globalValueSets/Level.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Beginner</fullName>
        <default>true</default>
        <label>Beginner</label>
    </customValue>
    <customValue>
        <fullName>Intermediate</fullName>
    </customValue>
    <customValue>
        <fullName>Advanced</fullName>
    </customValue>
    <masterLabel>Level</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/BadgeTrigger_Helper.cls
/**
 * @description       : A catchall trigger helper for TrailTrigger, BadgeTrigger, RecommendedBadgeTrigger, and RecommendedTrailTrigger.
 * @author            : Ben Learn
 * @group             : 
 * @last modified on  : 02-25-2022
 * @last modified by  : Ben Learn
**/
public without sharing class BadgeTrigger_Helper {
    public static final Map<String, ObjectInfoWrapper> objectInfoMap;

    static {
        objectInfoMap = new Map<String, ObjectInfoWrapper>();

        Map<String, String> badgeJunctionPicklists = new Map<String, String>();
        badgeJunctionPicklists.put('trailheadapp__Level__c', 'Level__c');
        badgeJunctionPicklists.put('trailheadapp__Type__c', 'Type__c');
        
        Map<String, String> trailJunctionPicklists = new Map<String, String>();
        trailJunctionPicklists.put('trailheadapp__Level__c', 'Level__c');

        objectInfoMap.put('trailheadapp__Badge__c', new ObjectInfoWrapper(badgeJunctionPicklists, 'Recommended_Badge__c', 'Badge__c'));
        objectInfoMap.put('trailheadapp__Trail__c', new ObjectInfoWrapper(trailJunctionPicklists, 'Recommended_Trail__c', 'Trail__c'));
    }

    public static void updateJunctionTypesAndLevels(List<sObject> oldRecords, Map<Id, sObject> newRecordMap, String sObjectType) {
        List<String> fieldsToCheck = new List<String>(objectInfoMap.get(sObjectType).parentJunctionPicklistMap.keySet());

        Set<Id> modifiedParentIds = new Set<Id>();

        for(sObject oldRecord : oldRecords) {
            for(String fieldToCheck : fieldsToCheck) {
                if(oldRecord.get(fieldToCheck) != newRecordMap.get(String.valueOf(oldRecord.get('Id'))).get(fieldToCheck)) {
                    modifiedParentIds.add(String.valueOf(oldRecord.get('Id')));
                }
            }
        }

        ObjectInfoWrapper parentObjectInfo = objectInfoMap.get(sObjectType);

        String queryString = 'SELECT ' + parentObjectInfo.relationshipFieldName + ', ' + String.join(fieldsToCheck, ', ') + ' FROM ' + parentObjectInfo.childJunctionObjectType +
            ' WHERE ' + parentObjectInfo.relationshipFieldName + ' IN :' + modifiedParentIds;

        List<sObject> junctionRecordsToUpdate = Database.query(queryString);

        for(sObject junctionRecord : junctionRecordsToUpdate) {
            for(String picklist : parentObjectInfo.parentJunctionPicklistMap.values()) {
                sObject parentRecord = newRecordMap.get(String.valueOf(junctionRecord.get(parentObjectInfo.relationshipFieldName)));
                junctionRecord.put(picklist, parentRecord.get(picklist));
            }
        }

        update junctionRecordsToUpdate;
    }

    private class ObjectInfoWrapper {
        Map<String, String> parentJunctionPicklistMap;
        String childJunctionObjectType;
        String relationshipFieldName;

        private ObjectInfoWrapper(Map<String, String> parentJunctionPicklistMap, String childJunctionObjectType, String relationshipFieldName) {
            this.parentJunctionPicklistMap = parentJunctionPicklistMap;
            this.childJunctionObjectType = childJunctionObjectType;
            this.relationshipFieldName = relationshipFieldName;
        }
    }
}