force-app/main/default/objects/Badge_to_Keep__mdt/Badge_to_Keep__mdt.object-meta.xml
<CustomObject>
    <label>Badge to Keep</label>
    <pluralLabel>Badges to Keep</pluralLabel>
</CustomObject>

CustomMetadataTypes/main/default/objects/Badge_to_Keep__mdt/fields/Badge_Name__c.field-meta.xml
<CustomField>
    <fullName>Badge_Name__c</fullName>
    <label>Badge Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

StorageManagement/main/default/classes/BadgesToKeepSelector.cls
/**
 * @description       : Selector class for Badge to Keep custom metadata type.
 * @author            : Ben Learn
 * @last modified on  : 01-22-2023
 * @last modified by  : Ben Learn
**/
public inherited sharing class BadgesToKeepSelector extends ApplicationSelector {
    public List<Schema.SObjectField> getSObjectFieldList() {
        return new List<Schema.SObjectField> {
            Badge_to_Keep__mdt.Badge_Name__c
        };
    }

    public Schema.SObjectType getSObjectType() {
        return Badge_to_Keep__mdt.sObjectType;
    }
}