force-app/main/default/objects/Badge_to_Keep__mdt/Badge_to_Keep__mdt.object-meta.xml
<CustomObject>
    <label>Badge to Keep</label>
    <pluralLabel>Badges to Keep</pluralLabel>
</CustomObject>

CustomMetadataTypes/main/default/objects/Badge_to_Keep__mdt/fields/Badge_Name__c.field-meta.xml
<CustomField>
    <fullName>Badge_Name__c</fullName>
    <label>Badge Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

StorageManagement/main/default/classes/BadgesToKeepSelectorTests.cls
/**
 * @description       : Test class for BadgesToKeepSelector.
 * @author            : Ben Learn
 * @last modified on  : 01-22-2023
 * @last modified by  : Ben Learn
**/
@isTest
private class BadgesToKeepSelectorTests {
    @isTest
    private static void getSObjectFieldList_test() {
        List<Schema.SObjectField> expectedFieldList = new List<Schema.SObjectField> {
            Badge_to_Keep__mdt.Badge_Name__c
        };

        Assert.areEqual(expectedFieldList, new BadgesToKeepSelector().getSObjectFieldList(), SelectorTestErrorMessages.SOBJECT_FIELD_LIST_ERROR_MESSAGE);
    }

    @isTest
    private static void getSObjectType_test() {
        Assert.areEqual(Badge_to_Keep__mdt.sObjectType, new BadgesToKeepSelector().getSObjectType(), SelectorTestErrorMessages.SOBJECT_TYPE_ERROR_MESSAGE);
    }
}