DataModel/main/default/objects/DefaultServiceImplementation__mdt/DefaultServiceImplementation__mdt.object-meta.xml
<CustomObject>
    <label>Default Service Implementation</label>
    <pluralLabel>Default Service Implementations</pluralLabel>
</CustomObject>

Core/main/default/objects/DefaultServiceImplementation__mdt/fields/DefaultImplementation__c.field-meta.xml
<CustomField>
    <fullName>DefaultImplementation__c</fullName>
    <label>Default Implementation</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

DataModel/main/default/classes/Application.cls
/**
 * @description       : Application class for fflib Factory definitions.
 * @author            : Ben Learn
 * @last modified on  : 01-08-2023
 * @last modified by  : Ben Learn
**/
public class Application {
    private static Map<Type, Type> defaultServiceImplementationMap = new Map<Type, Type>();
    static {
        List<DefaultServiceImplementation__mdt> defaultServiceImplementations = [
            SELECT DeveloperName, DefaultImplementation__c FROM DefaultServiceImplementation__mdt
        ];
        for(DefaultServiceImplementation__mdt dsi : defaultServiceImplementations) {
            defaultServiceImplementationMap.put(Type.forName(dsi.DeveloperName), Type.forName(dsi.DefaultImplementation__c));
        }
    }
    public static final fflib_Application.ServiceFactory Service = new fflib_Application.ServiceFactory(defaultServiceImplementationMap);
}