DataModel/main/default/objects/DefaultServiceImplementation__mdt/DefaultServiceImplementation__mdt.object-meta.xml
<CustomObject>
    <label>Default Service Implementation</label>
    <pluralLabel>Default Service Implementations</pluralLabel>
</CustomObject>

Core/main/default/objects/DefaultServiceImplementation__mdt/fields/DefaultImplementation__c.field-meta.xml
<CustomField>
    <fullName>DefaultImplementation__c</fullName>
    <label>Default Implementation</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Core/classes/tests/DefaultServiceImplementationSelectorTest.cls
@isTest
private class DefaultServiceImplementationSelectorTest {
    @isTest
    private static void getSObjectFieldList_test() {
        List<Schema.SObjectField> expectedFieldList = new List<Schema.SObjectField> {
            DefaultServiceImplementation__mdt.DeveloperName,
            DefaultServiceImplementation__mdt.DefaultImplementation__c
        };

        Assert.areEqual(expectedFieldList, new DefaultServiceImplementationsSelector().getSObjectFieldList(), SelectorTestErrorMessages.SOBJECT_FIELD_LIST_ERROR_MESSAGE);
    }

    @isTest
    private static void getSObjectType_test() {
        Assert.areEqual(DefaultServiceImplementation__mdt.sObjectType, new DefaultServiceImplementationsSelector().getSObjectType(), SelectorTestErrorMessages.SOBJECT_TYPE_ERROR_MESSAGE);
    }

    @isTest
    private static void selectAll_test() {
        List<DefaultServiceImplementation__mdt> expectedDefaultServiceImplementations = [SELECT DeveloperName, DefaultImplementation__c FROM DefaultServiceImplementation__mdt];
        List<DefaultServiceImplementation__mdt> resultDefaultServiceImplementations = new DefaultServiceImplementationsSelector().selectAll();
        Assert.areEqual(expectedDefaultServiceImplementations, resultDefaultServiceImplementations, 'Expected all DefaultServiceImplementation records to be returned.');
    }
}