DataModel/main/default/objects/DefaultServiceImplementation__mdt/DefaultServiceImplementation__mdt.object-meta.xml
<CustomObject>
    <label>Default Service Implementation</label>
    <pluralLabel>Default Service Implementations</pluralLabel>
</CustomObject>

Core/main/default/objects/DefaultServiceImplementation__mdt/fields/DefaultImplementation__c.field-meta.xml
<CustomField>
    <fullName>DefaultImplementation__c</fullName>
    <label>Default Implementation</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Core/main/default/classes/DefaultServiceImplementationsSelector.cls
/**
 * @description       : Selector class for Default Service Implementation custom metadata type.
 * @author            : Ben Learn
 * @last modified on  : 01-22-2023
 * @last modified by  : Ben Learn
**/
public inherited sharing class DefaultServiceImplementationsSelector extends ApplicationSelector {
    public List<Schema.SObjectField> getSObjectFieldList() {
        return new List<Schema.SObjectField> {
            DefaultServiceImplementation__mdt.DeveloperName,
            DefaultServiceImplementation__mdt.DefaultImplementation__c
        };
    }

    public Schema.SObjectType getSObjectType() {
        return DefaultServiceImplementation__mdt.sObjectType;
    }

    public List<DefaultServiceImplementation__mdt> selectAll() {
        return (List<DefaultServiceImplementation__mdt>) Database.query(newQueryFactory().toSOQL());
    }
}