Core/main/default/objects/DefaultObjectSelector__mdt/DefaultObjectSelector__mdt.object-meta.xml
<CustomObject>
    <label>Default Object Selector</label>
    <pluralLabel>Default Object Selectors</pluralLabel>
</CustomObject>

Core/objects/DefaultObjectSelector__mdt/fields/DefaultSelector__c.field-meta.xml
<CustomField>
    <fullName>DefaultSelector__c</fullName>
    <label>Default Selector</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

Core/main/default/objects/DefaultObjectSelector__mdt/fields/Suffix__c.field-meta.xml
<CustomField>
    <fullName>Suffix__c</fullName>
    <label>Suffix</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>__c</fullName>
                <default>true</default>
                <label>__c</label>
            </value>
            <value>
                <fullName>__mdt</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Core/classes/tests/DefaultObjectSelectorsSelectorTests.cls
@isTest(IsParallel=true)
private class DefaultObjectSelectorsSelectorTests {
    @isTest
    private static void getSObjectFieldList_test() {
        List<Schema.SObjectField> expectedFieldList = new List<Schema.SObjectField> {
            DefaultObjectSelector__mdt.DeveloperName,
            DefaultObjectSelector__mdt.DefaultSelector__c,
            DefaultObjectSelector__mdt.Suffix__c
        };

        Assert.areEqual(expectedFieldList, new DefaultObjectSelectorsSelector().getSObjectFieldList(), SelectorTestErrorMessages.SOBJECT_FIELD_LIST_ERROR_MESSAGE);
    }

    @isTest
    private static void getSObjectType_test() {
        Assert.areEqual(DefaultObjectSelector__mdt.sObjectType, new DefaultObjectSelectorsSelector().getSObjectType(), SelectorTestErrorMessages.SOBJECT_TYPE_ERROR_MESSAGE);
    }

    @isTest
    private static void selectAll_test() {
        Map<Id, DefaultObjectSelector__mdt> expectedDefaultObjectSelectorsById = new Map<Id, DefaultObjectSelector__mdt>([SELECT Id FROM DefaultObjectSelector__mdt]);
        Map<Id, DefaultObjectSelector__mdt> resultDefaultObjectSelectorsById = new Map<Id, DefaultObjectSelector__mdt>(new DefaultObjectSelectorsSelector().selectAll());

        Assert.areEqual(expectedDefaultObjectSelectorsById.keySet(), resultDefaultObjectSelectorsById.keySet(), 'Expected all DefaultObjectSelector records to be returned.');
    }
}