Core/main/default/objects/DefaultObjectSelector__mdt/DefaultObjectSelector__mdt.object-meta.xml
<CustomObject>
    <label>Default Object Selector</label>
    <pluralLabel>Default Object Selectors</pluralLabel>
</CustomObject>

Core/objects/DefaultObjectSelector__mdt/fields/DefaultSelector__c.field-meta.xml
<CustomField>
    <fullName>DefaultSelector__c</fullName>
    <label>Default Selector</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

Core/main/default/objects/DefaultObjectSelector__mdt/fields/Suffix__c.field-meta.xml
<CustomField>
    <fullName>Suffix__c</fullName>
    <label>Suffix</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>__c</fullName>
                <default>true</default>
                <label>__c</label>
            </value>
            <value>
                <fullName>__mdt</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Core/classes/DefaultObjectSelectorsSelector.cls
/**
 * @description       : Selector class for Default Object Selector custom metadata type.
 * @author            : Ben Learn
 * @last modified on  : 01-29-2023
 * @last modified by  : Ben Learn
**/
public inherited sharing class DefaultObjectSelectorsSelector extends ApplicationSelector {
    public List<Schema.SObjectField> getSObjectFieldList() {
        return new List<Schema.SObjectField> {
            DefaultObjectSelector__mdt.DeveloperName,
            DefaultObjectSelector__mdt.DefaultSelector__c,
            DefaultObjectSelector__mdt.Suffix__c
        };
    }

    public Schema.SObjectType getSObjectType() {
        return DefaultObjectSelector__mdt.sObjectType;
    }

    public List<DefaultObjectSelector__mdt> selectAll() {
        return (List<DefaultObjectSelector__mdt>) Database.query(newQueryFactory().toSOQL());
    }
}