Core/main/default/objects/DefaultObjectSelector__mdt/DefaultObjectSelector__mdt.object-meta.xml
<CustomObject>
    <label>Default Object Selector</label>
    <pluralLabel>Default Object Selectors</pluralLabel>
</CustomObject>

Core/objects/DefaultObjectSelector__mdt/fields/DefaultSelector__c.field-meta.xml
<CustomField>
    <fullName>DefaultSelector__c</fullName>
    <label>Default Selector</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

Core/main/default/objects/DefaultObjectSelector__mdt/fields/Suffix__c.field-meta.xml
<CustomField>
    <fullName>Suffix__c</fullName>
    <label>Suffix</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>__c</fullName>
                <default>true</default>
                <label>__c</label>
            </value>
            <value>
                <fullName>__mdt</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

DataModel/main/default/objects/DefaultServiceImplementation__mdt/DefaultServiceImplementation__mdt.object-meta.xml
<CustomObject>
    <label>Default Service Implementation</label>
    <pluralLabel>Default Service Implementations</pluralLabel>
</CustomObject>

Core/main/default/objects/DefaultServiceImplementation__mdt/fields/DefaultImplementation__c.field-meta.xml
<CustomField>
    <fullName>DefaultImplementation__c</fullName>
    <label>Default Implementation</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Core/main/default/objects/Mix_Category__c/Mix_Category__c.object-meta.xml
<CustomObject>
    <label>Mix Category</label>
    <nameField>
        <label>Mix Category</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mix Categories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Core/objects/Mix_Category__c/fields/Recommended_Badge_Mix__c.field-meta.xml
<CustomField>
    <fullName>Recommended_Badge_Mix__c</fullName>
    <label>Recommended Badge Mix</label>
    <referenceTo>Recommended_Badge_Mix__c</referenceTo>
    <relationshipLabel>Mix Categories</relationshipLabel>
    <relationshipName>Mix_Categories</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Core/objects/Recommended_Badge__c/Recommended_Badge__c.object-meta.xml
<CustomObject>
    <description>Recommended Trailhead badge.</description>
    <label>Recommended Badge</label>
    <nameField>
        <displayFormat>RB-{0000000}</displayFormat>
        <label>Recommended Badge Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Recommended Badges</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Core/objects/Recommended_Badge__c/fields/Mix_Category__c.field-meta.xml
<CustomField>
    <fullName>Mix_Category__c</fullName>
    <label>Mix Category</label>
    <referenceTo>Mix_Category__c</referenceTo>
    <relationshipLabel>Recommended Badges</relationshipLabel>
    <relationshipName>Recommended_Badges</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Recommended_Badge__c/fields/Recommended_Badge_Mix__c.field-meta.xml
<CustomField>
    <fullName>Recommended_Badge_Mix__c</fullName>
    <label>Recommended Badge Mix</label>
    <referenceTo>Recommended_Badge_Mix__c</referenceTo>
    <relationshipLabel>Recommended Badges</relationshipLabel>
    <relationshipName>Recommended_Badges</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Core/main/default/objects/Recommended_Badge_Mix__c/Recommended_Badge_Mix__c.object-meta.xml
<CustomObject>
    <label>Recommended Badge Mix</label>
    <nameField>
        <label>Mix Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Recommended Badge Mixes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Core/main/default/objects/Recommended_Trail__c/Recommended_Trail__c.object-meta.xml
<CustomObject>
    <label>Recommended Trail</label>
    <nameField>
        <displayFormat>RT-{0000000}</displayFormat>
        <label>Recommended Trail Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Recommended Trails</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Core/objects/Recommended_Trail__c/fields/Mix_Category__c.field-meta.xml
<CustomField>
    <fullName>Mix_Category__c</fullName>
    <label>Mix Category</label>
    <referenceTo>Mix_Category__c</referenceTo>
    <relationshipLabel>Recommended Trails</relationshipLabel>
    <relationshipName>Recommended_Trails</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Recommended_Trail__c/fields/Recommended_Badge_Mix__c.field-meta.xml
<CustomField>
    <fullName>Recommended_Badge_Mix__c</fullName>
    <label>Recommended Badge Mix</label>
    <referenceTo>Recommended_Badge_Mix__c</referenceTo>
    <relationshipLabel>Recommended Trails</relationshipLabel>
    <relationshipName>Recommended_Trails</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Core/main/default/classes/Application.cls
/**
 * @description       : Application class for fflib Factory definitions.
 * @author            : Ben Learn
 * @last modified on  : 03-04-2023
 * @last modified by  : Ben Learn
**/
public class Application {
    // Service factory instantiation
    private static Map<Type, Type> defaultServiceImplementationMap = new Map<Type, Type>();
    static {
        List<DefaultServiceImplementation__mdt> defaultServiceImplementations = new DefaultServiceImplementationsSelector().selectAll();
        for(DefaultServiceImplementation__mdt dsi : defaultServiceImplementations) {
            defaultServiceImplementationMap.put(Type.forName(dsi.DeveloperName), Type.forName(dsi.DefaultImplementation__c));
        }
    }
    public static final fflib_Application.ServiceFactory Service = new fflib_Application.ServiceFactory(defaultServiceImplementationMap);

    // Selector factory instantiation
    private static Map<SObjectType, Type> selectorsBySObject = new Map<SObjectType, Type>();
    static {
        selectorsBySObject.put(AsyncApexJob.sObjectType, AsyncApexJobsSelector.class);
        selectorsBySObject.put(DefaultServiceImplementation__mdt.sObjectType, DefaultServiceImplementationsSelector.class);
        selectorsBySObject.put(Mix_Category__c.sObjectType, MixCategoriesSelector.class);
        selectorsBySObject.put(Recommended_Badge_Mix__c.sObjectType, RecommendedBadgeMixesSelector.class);
        selectorsBySObject.put(Recommended_Badge__c.sObjectType, RecommendedBadgesSelector.class);
        selectorsBySObject.put(Recommended_Trail__c.sObjectType, RecommendedTrailsSelector.class);
        selectorsBySObject.put(Task.sObjectType, TasksSelector.class);
        selectorsBySObject.put(trailheadapp__Badge__c.sObjectType, BadgesSelector.class);
        selectorsBySObject.put(trailheadapp__Debug_Log__c.sObjectType, DebugLogsSelector.class);
        selectorsBySObject.put(trailheadapp__Trailmix__c.sObjectType, TrailmixesSelector.class);
        selectorsBySObject.put(trailheadapp__Trail__c.sObjectType, TrailsSelector.class);
        selectorsBySObject.put(trailheadapp__User_Badge__c.sObjectType, UserBadgesSelector.class);

        List<DefaultObjectSelector__mdt> defaultObjectSelectors = new DefaultObjectSelectorsSelector().selectAll();
        for(DefaultObjectSelector__mdt defaultObjectSelector : defaultObjectSelectors) {
            selectorsBySObject.put(
                Schema.describeSObjects(new List<String>{defaultObjectSelector.DeveloperName + defaultObjectSelector.Suffix__c})[0].getSObjectType(), 
                Type.forName(defaultObjectSelector.DefaultSelector__c)
            );
        }
    }
    public static final fflib_Application.SelectorFactory Selector = new fflib_Application.SelectorFactory(selectorsBySObject);
}