Triggers/objects/NewRecommendedBadgeTrailEvent__e/NewRecommendedBadgeTrailEvent__e.object-meta.xml
<CustomObject>
    <description>Platform event published when new Recommended Badge/Recommended Trail records are created in bulk (i.e. more than 50 at a time).</description>
    <label>New Recommended Badge Trail Event</label>
    <pluralLabel>New Recommended Badge Trail Events</pluralLabel>
</CustomObject>

Triggers/objects/NewRecommendedBadgeTrailEvent__e/fields/RecordID__c.field-meta.xml
<CustomField>
    <fullName>RecordID__c</fullName>
    <description>Id of the newly created Recommended Badge/Recommended Trail.</description>
    <label>Record ID</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

Triggers/classes/tests/NewRecommendedBadgeTrailEventTgr_Tests.cls
@isTest
private class NewRecommendedBadgeTrailEventTgr_Tests {
    @isTest
    private static void it_should_queue_jobs_for_events() {
        RecommendedBadgeTS badgeGenerator = new RecommendedBadgeTS(new Map<String, Object>{
            'generateMasterRecords' => false,
            'numberToGenerate' => 25
        });
        RecommendedTrailTS trailGenerator = new RecommendedTrailTS(new Map<String, Object>{
            'generateMasterRecords' => false,
            'numberToGenerate' => 25
        });
        List<Id> recordIDs = new List<Id>();
        recordIDs.addAll((new Map<Id, sObject>(badgeGenerator.generate())).keySet());
        recordIDs.addAll((new Map<Id, sObject>(trailGenerator.generate())).keySet());
        NewRecommendedBadgeTrailEventTS recordEventGenerator = new NewRecommendedBadgeTrailEventTS(
            new Map<String, Object>{'numberToGenerate' => 50}, 
            new List<TestSupport.TestDataField>{new ControlledValueField(NewRecommendedBadgeTrailEvent__e.RecordID__c, recordIDs)}
        );
        Test.setMock(HttpCalloutMock.class, new CustomHttpCalloutMock('', 200));

        Test.startTest();
        EventBus.publish(recordEventGenerator.generate());
        Test.getEventBus().deliver();
        List<AsyncApexJob> queuedJobs = [SELECT Id FROM AsyncApexJob WHERE ApexClass.Name = 'QueueableTrailTrackerProviderCallout' AND JobType = 'Queueable' AND Status = 'Queued'];
        Assert.areEqual(50, queuedJobs.size(), 'Expected one queued Trail Tracker Provider for each NewRecommendedBadgeTrailEvent__e.');

        for(AsyncApexJob job : queuedJobs) {
            System.abortJob(job.Id);
        }
        Test.stopTest();
    }
}