Triggers/objects/NewRecommendedBadgeTrailEvent__e/NewRecommendedBadgeTrailEvent__e.object-meta.xml
<CustomObject>
    <description>Platform event published when new Recommended Badge/Recommended Trail records are created in bulk (i.e. more than 50 at a time).</description>
    <label>New Recommended Badge Trail Event</label>
    <pluralLabel>New Recommended Badge Trail Events</pluralLabel>
</CustomObject>

Triggers/objects/NewRecommendedBadgeTrailEvent__e/fields/RecordID__c.field-meta.xml
<CustomField>
    <fullName>RecordID__c</fullName>
    <description>Id of the newly created Recommended Badge/Recommended Trail.</description>
    <label>Record ID</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

DataModel/main/default/objects/Recommended_Trail__c/Recommended_Trail__c.object-meta.xml
<CustomObject>
    <label>Recommended Trail</label>
    <nameField>
        <displayFormat>RT-{0000000}</displayFormat>
        <label>Recommended Trail Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Recommended Trails</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Recommended_Trail__c/fields/URL__c.field-meta.xml
<CustomField>
    <fullName>URL__c</fullName>
    <formula>Trail__r.trailheadapp__URL__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>URL</label>
    <type>Text</type>
</CustomField>

Triggers/objects/TrailheadEntityURLMapping__mdt/TrailheadEntityURLMapping__mdt.object-meta.xml
<CustomObject>
    <description>Custom metadata type to hold URL mappings for Badges, Projects, Superbadges, and Trails from the default https://developer.salesforce.com domain to the https://trailhead.salesforce.com domain.</description>
    <label>Trailhead Entity URL Mapping</label>
    <pluralLabel>Trailhead Entity URL Mappings</pluralLabel>
</CustomObject>

Triggers/objects/TrailheadEntityURLMapping__mdt/fields/DefaultPath__c.field-meta.xml
<CustomField>
    <fullName>DefaultPath__c</fullName>
    <description>Default path stored in the trailheadapp__URL__c field on the trailheadapp__Badge__c/trailheadapp__Trail__c record.</description>
    <label>Default Path</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

Triggers/objects/TrailheadEntityURLMapping__mdt/fields/TrailheadEntityType__c.field-meta.xml
<CustomField>
    <fullName>TrailheadEntityType__c</fullName>
    <description>Type of Trailhead Entity for URL mapping.</description>
    <label>Trailhead Entity Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Module</fullName>
                <default>true</default>
                <label>Module</label>
            </value>
            <value>
                <fullName>Project</fullName>
            </value>
            <value>
                <fullName>Superbadge</fullName>
            </value>
            <value>
                <fullName>Trail</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Triggers/objects/TrailheadEntityURLMapping__mdt/fields/TrailheadPath__c.field-meta.xml
<CustomField>
    <fullName>TrailheadPath__c</fullName>
    <description>Mapped Trailhead path for Trailhead Entity Type.</description>
    <label>Trailhead Path</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

Triggers/classes/RecommendedBadgeTrailTriggerHelper.cls
/**
 * Helper class for common functionality from RecommendedBadgeTriggerHandler and RecommendedTrailTriggerHandler.
 * @author Ben Learn
 * @since 06-10-2024
 */
public with sharing class RecommendedBadgeTrailTriggerHelper {
    @TestVisible
    private static Boolean enabledForTesting = false;

    @TestVisible
    private static final Map<String, URLMapping> TRAILHEAD_URL_MAPPINGS {
        get {
            if(TRAILHEAD_URL_MAPPINGS == null) {
                TRAILHEAD_URL_MAPPINGS = new Map<String, URLMapping>();
                List<TrailheadEntityURLMapping__mdt> urlMappings = [SELECT DefaultPath__c, TrailheadEntityType__c, TrailheadPath__c FROM TrailheadEntityURLMapping__mdt];
                for(TrailheadEntityURLMapping__mdt urlMapping : urlMappings) {
                    TRAILHEAD_URL_MAPPINGS.put(
                        urlMapping.TrailheadEntityType__c, 
                        new URLMapping(urlMapping.TrailheadEntityType__c, urlMapping.DefaultPath__c, urlMapping.TrailheadPath__c)
                    );
                }
            }
            return TRAILHEAD_URL_MAPPINGS;
        }
        set;
    }

    /**
     * Enqueues Trail Tracker Provider callouts to get field values for new Recommended Badges/Recommended Trails. If size of newRecordsMap is greater than the remaining Apex
     * governor limits for enqueueing jobs in a single transaction, enqueues as many Trail Tracker Provider callouts as possible without violating the governor limit and publishes
     * NewRecommendedBadgeTrailEvent__e platform events for the remaining new records.
     * @param entityType type of values in newRecordsMap
     * @param newRecordsMap records to enqueue Trail Tracker Provider callouts/publish NewRecommendedBadgeTrailEvent__e events for
     */    
    public static void queueTrailTrackerProviderCallouts(SObjectType entityType, Map<Id, sObject> newRecordsMap) {
        Boolean failedEnqueueingJob = false;
        Integer remainingQueueableJobs = Limits.getLimitQueueableJobs() - Limits.getQueueableJobs();

        // not making callouts for Recommended Badges/Trails inserted through the Bulk API, which is currently only used for scratch org data population
        if((Request.getCurrent().getQuiddity() == Quiddity.BULK_API) || (Test.isRunningTest() && !enabledForTesting)) {
            return;
        }
        List<NewRecommendedBadgeTrailEvent__e> newRecordEvents = new List<NewRecommendedBadgeTrailEvent__e>();
        for(String newRecordId : newRecordsMap.keySet()) {
            if(remainingQueueableJobs > 0) {
                try {
                    System.enqueueJob(new QueueableTrailTrackerProviderCallout(newRecordId));
                } catch(Exception e) {
                    failedEnqueueingJob = true;
                    Logger.error(new LogMessage('Error enqueueing callout to Trail Tracker Provider. {0}: {1}. \n{2}', e.getTypeName(), e.getMessage(), e.getStackTraceString()));
                }
                remainingQueueableJobs -= 1;
            } else {
                newRecordEvents.add(new NewRecommendedBadgeTrailEvent__e(RecordID__c = newRecordId));
            }
        }
        if(failedEnqueueingJob) {
            Logger.saveLog();
        }

        if(newRecordEvents.size() > 0) {
            List<Database.SaveResult> saveResults = EventBus.publish(newRecordEvents);
            DMLUtils.logErrors(saveResults, 'RecommendedBadgeTrailTriggerHelper');
        }
    }

    /**
     * Updates the value of the URL__c field on Recommended Badges/Trails from the https://developer.salesforce.com domain to the https://trailhead.salesforce.com domain.
     * @param entityType type of values in newRecords and oldRecordsMap
     * @param newRecords
     * @param oldRecordsMap 
     */    
    public static void updateURLPaths(SObjectType entityType, List<sObject> newRecords, Map<Id, sObject> oldRecordsMap) {
        if(oldRecordsMap == null) {
            for(sObject newRecord : newRecords) {
                if(newRecord.get('URL__c') != null) {
                    changeURL(entityType, newRecord);
                }
            }
        } else {
            for(sObject newRecord : newRecords) {
                if(newRecord.get('URL__c') != oldRecordsMap.get(String.valueOf(newRecord.get('Id'))).get('URL__c')) {
                    changeURL(entityType, newRecord);
                }
            }
        }
    }

    private static void changeURL(SObjectType entityType, sObject record) {
        URLMapping mapping = TRAILHEAD_URL_MAPPINGS.get(entityType.getDescribe().getName() == 'Recommended_Trail__c' ? 'Trail' : String.valueOf(record.get('Type__c')));
        record.put('URL__c', String.valueOf(record.get('URL__c')).replace(mapping.defaultPath, mapping.trailheadPath));
    }

    @TestVisible
    private class URLMapping {
        @TestVisible
        private String trailheadEntityType;
        @TestVisible
        private String defaultPath;
        @TestVisible
        private String trailheadPath;

        private URLMapping(String trailheadEntityType, String defaultPath, String trailheadPath) {
            this.trailheadEntityType = trailheadEntityType;
            this.defaultPath = defaultPath;
            this.trailheadPath = trailheadPath;
        }
    }
}