Core/main/default/objects/Mix_Category__c/Mix_Category__c.object-meta.xml
<CustomObject>
    <label>Mix Category</label>
    <nameField>
        <label>Mix Category</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mix Categories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Core/objects/Mix_Category__c/fields/Recommended_Badge_Mix__c.field-meta.xml
<CustomField>
    <fullName>Recommended_Badge_Mix__c</fullName>
    <label>Recommended Badge Mix</label>
    <referenceTo>Recommended_Badge_Mix__c</referenceTo>
    <relationshipLabel>Mix Categories</relationshipLabel>
    <relationshipName>Mix_Categories</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Core/main/default/objects/Recommended_Badge_Mix__c/Recommended_Badge_Mix__c.object-meta.xml
<CustomObject>
    <label>Recommended Badge Mix</label>
    <nameField>
        <label>Mix Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Recommended Badge Mixes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Core/classes/testsupport/MixCategoryTS.cls
@isTest
public class MixCategoryTS extends TestSupport.DataGeneration {
    public RecommendedBadgeMixTS badgeMixGenerator;

    @SuppressWarnings('PMD.ApexDoc')
    public MixCategoryTS(Map<String, Object> options) {
        this(options, new List<TestSupport.TestDataField>());
    }

    @SuppressWarnings('PMD.ApexDoc')
    public MixCategoryTS(Map<String, Object> options, List<TestSupport.TestDataField> fieldSpecs) {
        super(options, fieldSpecs);
        this.S_OBJECT_TYPE = 'Mix_Category__c';

        this.generateMasterRecords = Boolean.valueOf(options.get('generateMasterRecords') ?? true);
    }

    protected override Map<Schema.SObjectField, TestSupport.TestDataField> loadDefaultSpecsByField() {
        Map<Schema.SObjectField, TestSupport.TestDataField> defaultSpecsByField = new Map<Schema.SObjectField, TestSupport.TestDataField>{
            Mix_Category__c.Name => new CounterSuffixField(Mix_Category__c.Name, 'Test Category ')
        };
        return defaultSpecsByField;
    }

    protected override Map<Schema.SObjectField, RelationshipField> loadMasterDetailFields() {
        this.badgeMixGenerator = new RecommendedBadgeMixTS(new Map<String, Object>{'numberToGenerate' => 5});
        return new Map<Schema.SObjectField, RelationshipField>{
            Mix_Category__c.Recommended_Badge_Mix__c => new RelationshipField(
                Mix_Category__c.Recommended_Badge_Mix__c, 
                new Map<Id, sObject>(this.badgeMixGenerator.generate()).keySet()
            )
        };
    }
}