Core/main/default/objects/Mix_Category__c/Mix_Category__c.object-meta.xml
<CustomObject>
    <label>Mix Category</label>
    <nameField>
        <label>Mix Category</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mix Categories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Core/objects/Mix_Category__c/fields/Recommended_Badge_Mix__c.field-meta.xml
<CustomField>
    <fullName>Recommended_Badge_Mix__c</fullName>
    <label>Recommended Badge Mix</label>
    <referenceTo>Recommended_Badge_Mix__c</referenceTo>
    <relationshipLabel>Mix Categories</relationshipLabel>
    <relationshipName>Mix_Categories</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Core/objects/Recommended_Badge__c/Recommended_Badge__c.object-meta.xml
<CustomObject>
    <description>Recommended Trailhead badge.</description>
    <label>Recommended Badge</label>
    <nameField>
        <displayFormat>RB-{0000000}</displayFormat>
        <label>Recommended Badge Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Recommended Badges</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Core/objects/Recommended_Badge__c/fields/BadgeAPIName__c.field-meta.xml
<CustomField>
    <fullName>BadgeAPIName__c</fullName>
    <label>Badge API Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

Core/objects/Recommended_Badge__c/fields/BadgeName__c.field-meta.xml
<CustomField>
    <fullName>BadgeName__c</fullName>
    <description>Name of the corresponding trailheadapp__Badge__c.</description>
    <label>Badge Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

Core/main/default/objects/Recommended_Badge__c/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <label>Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Beginner</fullName>
                <default>true</default>
                <label>Beginner</label>
            </value>
            <value>
                <fullName>Intermediate</fullName>
            </value>
            <value>
                <fullName>Advanced</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Core/objects/Recommended_Badge__c/fields/Mix_Category__c.field-meta.xml
<CustomField>
    <fullName>Mix_Category__c</fullName>
    <label>Mix Category</label>
    <referenceTo>Mix_Category__c</referenceTo>
    <relationshipLabel>Recommended Badges</relationshipLabel>
    <relationshipName>Recommended_Badges</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Recommended_Badge__c/fields/Recommended_Badge_Mix__c.field-meta.xml
<CustomField>
    <fullName>Recommended_Badge_Mix__c</fullName>
    <label>Recommended Badge Mix</label>
    <referenceTo>Recommended_Badge_Mix__c</referenceTo>
    <relationshipLabel>Recommended Badges</relationshipLabel>
    <relationshipName>Recommended_Badges</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Core/objects/Recommended_Badge__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Value of trailheadapp__Type__c field on corresponding trailheadapp__Badge__c.</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Module</fullName>
                <default>true</default>
                <label>Module</label>
            </value>
            <value>
                <fullName>Project</fullName>
            </value>
            <value>
                <fullName>Superbadge</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Core/main/default/objects/Recommended_Badge_Mix__c/Recommended_Badge_Mix__c.object-meta.xml
<CustomObject>
    <label>Recommended Badge Mix</label>
    <nameField>
        <label>Mix Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Recommended Badge Mixes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Core/objects/Recommended_Badge_Mix__c/fields/Private_Mix__c.field-meta.xml
<CustomField>
    <fullName>Private_Mix__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Private Mix</label>
    <type>Checkbox</type>
</CustomField>

Core/classes/selectors/RecommendedBadgesSelector.cls
/**
 * Selector class for Recommended Badge custom object.
 * @author Ben Learn
 * @since 02-16-2023
 * @group Core
 */
public inherited sharing class RecommendedBadgesSelector extends ApplicationSelector {
    /**
     * fflib method to hold the fields to always be queried by the selector
     * @return  `List<Schema.SObjectField>`
     */
    public List<Schema.SObjectField> getSObjectFieldList() {
        return new List<Schema.SObjectField> {
            Recommended_Badge__c.Id,
            Recommended_Badge__c.Level__c,
            Recommended_Badge__c.Type__c
        };
    }

    /**
     * fflib method to return the sObjectType of the object being queried
     * @return  `Schema.SObjectType`
     */
    public Schema.sObjectType getSObjectType() {
        return Recommended_Badge__c.sObjectType;
    }

    /**
     * Returns all Recommended_Badge__c records that have a matching BadgeAPIName__c, including fields in the Core field set
     * @param badgeAPINames 
     * @return  `List<Recommended_Badge__c>`
     */
    public List<Recommended_Badge__c> selectBadgesByAPINames(Set<String> badgeAPINames) {
        return (List<Recommended_Badge__c>) Database.query(
            newQueryFactory().selectFieldSet(Schema.SObjectType.Recommended_Badge__c.fieldSets.Core, false).
            setCondition('BadgeAPIName__c IN :badgeAPINames').
            toSOQL()
        );
    }

    /**
     * Returns all Recommended_Badge__c records related to the private mix of the running user, including fields from the PrivateMixView field set
     * @return  `List<Recommended_Badge__c>`
     */
    public List<Recommended_Badge__c> selectedAllRelatedToUserPrivateMix() {
        fflib_QueryFactory recommendedBadgesQueryFactory = newQueryFactory();

        new MixCategoriesSelector().configureQueryFactoryFields(recommendedBadgesQueryFactory, Recommended_Badge__c.Mix_Category__c.getDescribe().getRelationshipName());

        return (List<Recommended_Badge__c>) Database.query(
            recommendedBadgesQueryFactory.selectFieldSet(Schema.SObjectType.Recommended_Badge__c.fieldSets.PrivateMixView, true).
            setCondition('Mix_Category__r.Recommended_Badge_Mix__r.Private_Mix__c = true AND Mix_Category__r.Recommended_Badge_Mix__r.OwnerId = \'' + UserInfo.getUserId() + '\'').
            setOrdering(new fflib_QueryFactory.Ordering(
                this.getSObjectType().getDescribe().getName(), 
                Schema.SObjectType.Recommended_Badge__c.fields.BadgeName__c.getName(), 
                fflib_QueryFactory.SortOrder.ASCENDING
            )).
            toSOQL()
        );
    }

    /**
     * Returns the API name of the Recommended_Badge__c with the provided Id by including fields from the Triggers field set
     * @param recommendedBadgeId 
     * @return  `Recommended_Badge__c`
     */
    public Recommended_Badge__c selectBadgeAPINameById(Id recommendedBadgeId) {
        return (Recommended_Badge__c) Database.query(
            newQueryFactory().selectFieldSet(Schema.SObjectType.Recommended_Badge__c.fieldSets.Triggers, false).
            setCondition('Id = \'' + recommendedBadgeId + '\'').
            toSOQL()
        )[0];
    }
}