Core/main/default/objects/Mix_Category__c/Mix_Category__c.object-meta.xml
<CustomObject>
    <label>Mix Category</label>
    <nameField>
        <label>Mix Category</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mix Categories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Core/objects/Mix_Category__c/fields/Recommended_Badge_Mix__c.field-meta.xml
<CustomField>
    <fullName>Recommended_Badge_Mix__c</fullName>
    <label>Recommended Badge Mix</label>
    <referenceTo>Recommended_Badge_Mix__c</referenceTo>
    <relationshipLabel>Mix Categories</relationshipLabel>
    <relationshipName>Mix_Categories</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Core/objects/Recommended_Badge__c/Recommended_Badge__c.object-meta.xml
<CustomObject>
    <description>Recommended Trailhead badge.</description>
    <label>Recommended Badge</label>
    <nameField>
        <displayFormat>RB-{0000000}</displayFormat>
        <label>Recommended Badge Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Recommended Badges</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

DataModel/main/default/objects/Recommended_Badge__c/fields/Archived__c.field-meta.xml
<CustomField>
    <fullName>Archived__c</fullName>
    <formula>Badge__r.trailheadapp__Archived__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Archived</label>
    <type>Checkbox</type>
</CustomField>

Core/objects/Recommended_Badge__c/fields/BadgeAPIName__c.field-meta.xml
<CustomField>
    <fullName>BadgeAPIName__c</fullName>
    <label>Badge API Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

Core/objects/Recommended_Badge__c/fields/BadgeName__c.field-meta.xml
<CustomField>
    <fullName>BadgeName__c</fullName>
    <description>Name of the corresponding trailheadapp__Badge__c.</description>
    <label>Badge Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

Core/objects/Recommended_Badge__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Value of the trailheadapp__Description__c field on the corresponding trailheadapp__Badge__c.</description>
    <label>Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Core/objects/Recommended_Badge__c/fields/Icon__c.field-meta.xml
<CustomField>
    <fullName>Icon__c</fullName>
    <description>Value of the trailheadapp__Icon__c field on the corresponding trailheadapp__Badge__c.</description>
    <label>Icon</label>
    <type>Url</type>
</CustomField>

Core/main/default/objects/Recommended_Badge__c/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <label>Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Beginner</fullName>
                <default>true</default>
                <label>Beginner</label>
            </value>
            <value>
                <fullName>Intermediate</fullName>
            </value>
            <value>
                <fullName>Advanced</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Core/objects/Recommended_Badge__c/fields/Mix_Category__c.field-meta.xml
<CustomField>
    <fullName>Mix_Category__c</fullName>
    <label>Mix Category</label>
    <referenceTo>Mix_Category__c</referenceTo>
    <relationshipLabel>Recommended Badges</relationshipLabel>
    <relationshipName>Recommended_Badges</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

Core/objects/Recommended_Badge__c/fields/Products__c.field-meta.xml
<CustomField>
    <fullName>Products__c</fullName>
    <description>Value of the trailheadapp__Products__c on the corresponding trailheadapp__Badge__c.</description>
    <label>Products</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Recommended_Badge__c/fields/Recommended_Badge_Mix__c.field-meta.xml
<CustomField>
    <fullName>Recommended_Badge_Mix__c</fullName>
    <label>Recommended Badge Mix</label>
    <referenceTo>Recommended_Badge_Mix__c</referenceTo>
    <relationshipLabel>Recommended Badges</relationshipLabel>
    <relationshipName>Recommended_Badges</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Core/objects/Recommended_Badge__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Value of trailheadapp__Type__c field on corresponding trailheadapp__Badge__c.</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Module</fullName>
                <default>true</default>
                <label>Module</label>
            </value>
            <value>
                <fullName>Project</fullName>
            </value>
            <value>
                <fullName>Superbadge</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Core/objects/Recommended_Badge__c/fields/URL__c.field-meta.xml
<CustomField>
    <fullName>URL__c</fullName>
    <description>Value of the URL for the corresponding trailheadapp__Badge__c.</description>
    <label>URL</label>
    <type>Url</type>
</CustomField>

Core/main/default/objects/Recommended_Badge_Mix__c/Recommended_Badge_Mix__c.object-meta.xml
<CustomObject>
    <label>Recommended Badge Mix</label>
    <nameField>
        <label>Mix Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Recommended Badge Mixes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Core/main/default/objects/Recommended_Trail__c/Recommended_Trail__c.object-meta.xml
<CustomObject>
    <label>Recommended Trail</label>
    <nameField>
        <displayFormat>RT-{0000000}</displayFormat>
        <label>Recommended Trail Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Recommended Trails</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Recommended_Trail__c/fields/Archived__c.field-meta.xml
<CustomField>
    <fullName>Archived__c</fullName>
    <formula>Trail__r.trailheadapp__Archived__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Archived</label>
    <type>Checkbox</type>
</CustomField>

Core/objects/Recommended_Trail__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <formula>Trail__r.trailheadapp__Description__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Description</label>
    <type>Text</type>
</CustomField>

Core/objects/Recommended_Trail__c/fields/Icon__c.field-meta.xml
<CustomField>
    <fullName>Icon__c</fullName>
    <description>Value of the trailheadapp__Icon__c field on the corresponding trailheadapp__Trail__c.</description>
    <label>Icon</label>
    <type>Url</type>
</CustomField>

Core/objects/Recommended_Trail__c/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <description>Value of the trailheadapp__Level__c field on corresponding trailheadapp__Trail__c.</description>
    <label>Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Level</valueSetName>
    </valueSet>
</CustomField>

Core/objects/Recommended_Trail__c/fields/Mix_Category__c.field-meta.xml
<CustomField>
    <fullName>Mix_Category__c</fullName>
    <label>Mix Category</label>
    <referenceTo>Mix_Category__c</referenceTo>
    <relationshipLabel>Recommended Trails</relationshipLabel>
    <relationshipName>Recommended_Trails</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

Core/objects/Recommended_Trail__c/fields/Products__c.field-meta.xml
<CustomField>
    <fullName>Products__c</fullName>
    <formula>Trail__r.trailheadapp__Products__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Products</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Recommended_Trail__c/fields/Recommended_Badge_Mix__c.field-meta.xml
<CustomField>
    <fullName>Recommended_Badge_Mix__c</fullName>
    <label>Recommended Badge Mix</label>
    <referenceTo>Recommended_Badge_Mix__c</referenceTo>
    <relationshipLabel>Recommended Trails</relationshipLabel>
    <relationshipName>Recommended_Trails</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Core/objects/Recommended_Trail__c/fields/TrailAPIName__c.field-meta.xml
<CustomField>
    <fullName>TrailAPIName__c</fullName>
    <description>Value of the trailheadapp__API_Name__c field on the corresponding trailheadapp__Trail__c record.</description>
    <label>Trail API Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

Core/objects/Recommended_Trail__c/fields/TrailName__c.field-meta.xml
<CustomField>
    <fullName>TrailName__c</fullName>
    <description>Value of the Name field on the corresponding trailheadapp__Trail__c.</description>
    <label>Trail Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

Core/objects/Recommended_Trail__c/fields/URL__c.field-meta.xml
<CustomField>
    <fullName>URL__c</fullName>
    <formula>Trail__r.trailheadapp__URL__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>URL</label>
    <type>Text</type>
</CustomField>

Core/globalValueSets/Level.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Beginner</fullName>
        <default>true</default>
        <label>Beginner</label>
    </customValue>
    <customValue>
        <fullName>Intermediate</fullName>
    </customValue>
    <customValue>
        <fullName>Advanced</fullName>
    </customValue>
    <customValue>
        <fullName>Superbadge Unit</fullName>
    </customValue>
    <customValue>
        <fullName>Superbadge</fullName>
    </customValue>
    <customValue>
        <fullName>Super Set</fullName>
    </customValue>
    <masterLabel>Level</masterLabel>
</GlobalValueSet>

Core/classes/tests/TrailheadEntityService_Tests.cls
@isTest(IsParallel=true)
private class TrailheadEntityService_Tests {
    private static final Set<String> MAPPED_BADGE_FIELDS = new Set<String>{
        'Archived__c',
        'BadgeName__c',
        'Description__c',
        'Icon__c',
        'Level__c',
        'Products__c',
        'Type__c',
        'URL__c'
    };

    private static final Set<String> MAPPED_TRAIL_FIELDS = new Set<String>{
        'Archived__c',
        'Description__c',
        'Icon__c',
        'Level__c',
        'Products__c',
        'TrailName__c',
        'URL__c'
    };

    @testSetup
    private static void generateMasterRecords() {
        RecommendedBadgeMixTS badgeMixGenerator = new RecommendedBadgeMixTS(new Map<String, Object>{'generateRecordIDs' => false, 'numberToGenerate' => 10});
        insert badgeMixGenerator.generate();
        MixCategoryTS mixCategoryGenerator = new MixCategoryTS(
            new Map<String, Object>{'generateMasterRecords' => false, 'generateRecordIDs' => false, 'numberToGenerate' => 100},
            new List<TestSupport.TestDataField>{new RelationshipField(Mix_Category__c.Recommended_Badge_Mix__c, (new Map<Id, sObject>(badgeMixGenerator.records)).keySet())}  
        );
        insert mixCategoryGenerator.generate();
    }

    private static Map<String, Recommended_Badge__c> generateRecommendedBadgesByAPIName(Set<Id> mixCategoryIds) {
        RecommendedBadgeTS badgeGenerator = new RecommendedBadgeTS(
            new Map<String, Object>{'generateMasterRecords' => false, 'generateRecordIDs' => false},
            new List<TestSupport.TestDataField>{new RelationshipField(Recommended_Badge__c.Mix_Category__c, mixCategoryIds)}    
        );
        insert badgeGenerator.generate();

        badgeGenerator.clearField(Recommended_Badge__c.BadgeName__c).
            clearField(Recommended_Badge__c.Description__c).
            clearField(Recommended_Badge__c.Icon__c).
            clearField(Recommended_Badge__c.Type__c).
            clearField(Recommended_Badge__c.URL__c).
            changeField(Recommended_Badge__c.Level__c).
            changeField(Recommended_Badge__c.Products__c, 'New test products');
        
        Map<String, Recommended_Badge__c> badgesByAPIName = new Map<String, Recommended_Badge__c>();
        Recommended_Badge__c tempBadge;
        for(sObject badge : badgeGenerator.modifiedRecords) {
            tempBadge = new Recommended_Badge__c();
            for(String field : badge.getPopulatedFieldsAsMap().keySet()) {
                if(MAPPED_BADGE_FIELDS.contains(field) && (badge.get(field) != null)) {
                    tempBadge.put(field, badge.get(field));
                }
            }
            badgesByAPIName.put(String.valueOf(badge.get('BadgeAPIName__c')), tempBadge);
        }
        
        return badgesByAPIName;
    }

    private static Map<String, Recommended_Trail__c> generateRecommendedTrailsByAPIName(Set<Id> mixCategoryIds) {
        RecommendedTrailTS trailGenerator = new RecommendedTrailTS(
            new Map<String, Object>{'generateMasterRecords' => false, 'generateRecordIDs' => false},
            new List<TestSupport.TestDataField>{new RelationshipField(Recommended_Trail__c.Mix_Category__c, mixCategoryIds)}
        );
        insert trailGenerator.generate();


        trailGenerator.clearField(Recommended_Trail__c.TrailName__c).
            clearField(Recommended_Trail__c.Description__c).
            clearField(Recommended_Trail__c.Icon__c).
            clearField(Recommended_Trail__c.URL__c).
            changeField(Recommended_Trail__c.Level__c).
            changeField(Recommended_Trail__c.Products__c, 'New test products');
    
        Map<String, Recommended_Trail__c> trailsByAPIName = new Map<String, Recommended_Trail__c>();
        Recommended_Trail__c tempTrail;
        for(sObject trail : trailGenerator.modifiedRecords) {
            tempTrail = new Recommended_Trail__c();
            for(String field : trail.getPopulatedFieldsAsMap().keySet()) {
                if(MAPPED_TRAIL_FIELDS.contains(field) && (trail.get(field) != null)) {
                    tempTrail.put(field, trail.get(field));
                }
            }
            trailsByAPIName.put(String.valueOf(trail.get('TrailAPIName__c')), tempTrail);
        }

        return trailsByAPIName;
    }

    @isTest
    private static void it_should_update_badges_and_trails() {
        Set<Id> mixCategoryIds = (new Map<Id, sObject>([SELECT Id FROM Mix_Category__c])).keySet();
        Map<String, Recommended_Badge__c> badgesByAPIName = generateRecommendedBadgesByAPIName(mixCategoryIds);
        Map<String, Recommended_Trail__c> trailsByAPIName = generateRecommendedTrailsByAPIName(mixCategoryIds);

        Test.startTest();
        TrailheadEntityService.doPatch(badgesByAPIName, trailsByAPIName);
        Test.stopTest();

        List<Recommended_Badge__c> updatedBadges = [SELECT BadgeAPIName__c, Level__c, Products__c FROM Recommended_Badge__c];
        List<Recommended_Trail__c> updatedTrails = [SELECT TrailAPIName__c, Level__c, Products__c FROM Recommended_Trail__c];
        for(Recommended_Badge__c badge : updatedBadges) {
            Assert.areEqual(badgesByAPIName.get(badge.BadgeAPIName__c).Level__c, badge.Level__c, 'Expected Recommended Badge level to be updated by PATCH call.');
            Assert.areEqual(badgesByAPIName.get(badge.BadgeAPIName__c).Products__c, badge.Products__c, 'Expected Recommended Badge products field to be updated by PATCH call.');
        }
        for(Recommended_Trail__c trail : updatedTrails) {
            Assert.areEqual(trailsByAPIName.get(trail.TrailAPIName__c).Level__c, trail.Level__c, 'Expected Recommended Trail level to be updated by PATCH call.');
            Assert.areEqual(trailsByAPIName.get(trail.TrailAPIName__c).Products__c, trail.Products__c, 'Expected Recommended Trail products field to be updated by PATCH call.');
        }
    }

    @isTest
    private static void it_should_update_badges_with_same_name_in_different_mixes() {
        

    }

    @isTest
    private static void it_should_update_badges_when_no_trail_updates() {
        Set<Id> mixCategoryIds = (new Map<Id, sObject>([SELECT Id FROM Mix_Category__c])).keySet();
        Map<String, Recommended_Badge__c> badgesByAPIName = generateRecommendedBadgesByAPIName(mixCategoryIds);

        Test.startTest();
        TrailheadEntityService.doPatch(badgesByAPIName, new Map<String, Recommended_Trail__c>());
        Test.stopTest();

        List<Recommended_Badge__c> updatedBadges = [SELECT BadgeAPIName__c, Level__c, Products__c FROM Recommended_Badge__c];
        for(Recommended_Badge__c badge : updatedBadges) {
            Assert.areEqual(badgesByAPIName.get(badge.BadgeAPIName__c).Level__c, badge.Level__c, 'Expected Recommended Badge level to be updated by PATCH call.');
            Assert.areEqual(badgesByAPIName.get(badge.BadgeAPIName__c).Products__c, badge.Products__c, 'Expected Recommended Badge products field to be updated by PATCH call.');
        }
    }

    @isTest
    private static void it_should_update_trails_when_no_badge_updates() {
        Set<Id> mixCategoryIds = (new Map<Id, sObject>([SELECT id FROM Mix_Category__c])).keySet();
        Map<String, Recommended_Trail__c> trailsByAPIName = generateRecommendedTrailsByAPIName(mixCategoryIds);

        Test.startTest();
        TrailheadEntityService.doPatch(new Map<String, Recommended_Badge__c>(), trailsByAPIName);
        Test.stopTest();

        List<Recommended_Trail__c> updatedTrails = [SELECT TrailAPIName__c, Level__c, Products__c FROM Recommended_Trail__c];
        for(Recommended_Trail__c trail : updatedTrails) {
            Assert.areEqual(trailsByAPIName.get(trail.TrailAPIName__c).Level__c, trail.Level__c, 'Expected Recommended Trail level to be updated by PATCH call.');
            Assert.areEqual(trailsByAPIName.get(trail.TrailAPIName__c).Products__c, trail.Products__c, 'Expected Recommended Trail products field to be updated by PATCH call.');
        }
    }

    @isTest
    private static void it_should_throw_exception_when_badge_updates_fail() {
        Set<Id> mixCategoryIds = (new Map<Id, sObject>([SELECT id FROM Mix_Category__c])).keySet();
        Map<String, Recommended_Badge__c> badgesByAPIName = generateRecommendedBadgesByAPIName(mixCategoryIds);
        //badgesByAPIName.values()[0]
        //new Map<String, Recommended_Badge__c>
    }

    @isTest
    private static void it_should_throw_exception_when_trail_updates_fail() {

    }

    @isTest
    private static void it_should_throw_exception_when_badge_and_trail_updates_fail() {
        
    }
}