Core/main/default/objects/Mix_Category__c/Mix_Category__c.object-meta.xml
<CustomObject>
    <label>Mix Category</label>
    <nameField>
        <label>Mix Category</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mix Categories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Core/main/default/objects/Recommended_Trail__c/Recommended_Trail__c.object-meta.xml
<CustomObject>
    <label>Recommended Trail</label>
    <nameField>
        <displayFormat>RT-{0000000}</displayFormat>
        <label>Recommended Trail Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Recommended Trails</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Core/objects/Recommended_Trail__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <formula>Trail__r.trailheadapp__Description__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Description</label>
    <type>Text</type>
</CustomField>

Core/objects/Recommended_Trail__c/fields/Icon__c.field-meta.xml
<CustomField>
    <fullName>Icon__c</fullName>
    <description>Value of the trailheadapp__Icon__c field on the corresponding trailheadapp__Trail__c.</description>
    <label>Icon</label>
    <type>Url</type>
</CustomField>

Core/objects/Recommended_Trail__c/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <description>Value of the trailheadapp__Level__c field on corresponding trailheadapp__Trail__c.</description>
    <label>Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Level</valueSetName>
    </valueSet>
</CustomField>

Core/objects/Recommended_Trail__c/fields/Mix_Category__c.field-meta.xml
<CustomField>
    <fullName>Mix_Category__c</fullName>
    <label>Mix Category</label>
    <referenceTo>Mix_Category__c</referenceTo>
    <relationshipLabel>Recommended Trails</relationshipLabel>
    <relationshipName>Recommended_Trails</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

Core/objects/Recommended_Trail__c/fields/Products__c.field-meta.xml
<CustomField>
    <fullName>Products__c</fullName>
    <formula>Trail__r.trailheadapp__Products__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Products</label>
    <type>Text</type>
</CustomField>

Core/objects/Recommended_Trail__c/fields/TrailAPIName__c.field-meta.xml
<CustomField>
    <fullName>TrailAPIName__c</fullName>
    <description>Value of the trailheadapp__API_Name__c field on the corresponding trailheadapp__Trail__c record.</description>
    <label>Trail API Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

Core/objects/Recommended_Trail__c/fields/TrailName__c.field-meta.xml
<CustomField>
    <fullName>TrailName__c</fullName>
    <description>Value of the Name field on the corresponding trailheadapp__Trail__c.</description>
    <label>Trail Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

Core/objects/Recommended_Trail__c/fields/URL__c.field-meta.xml
<CustomField>
    <fullName>URL__c</fullName>
    <formula>Trail__r.trailheadapp__URL__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>URL</label>
    <type>Text</type>
</CustomField>

Core/globalValueSets/Level.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Beginner</fullName>
        <default>true</default>
        <label>Beginner</label>
    </customValue>
    <customValue>
        <fullName>Intermediate</fullName>
    </customValue>
    <customValue>
        <fullName>Advanced</fullName>
    </customValue>
    <customValue>
        <fullName>Superbadge Unit</fullName>
    </customValue>
    <customValue>
        <fullName>Superbadge</fullName>
    </customValue>
    <customValue>
        <fullName>Super Set</fullName>
    </customValue>
    <masterLabel>Level</masterLabel>
</GlobalValueSet>

Core/classes/testsupport/RecommendedTrailTS.cls
@isTest
public class RecommendedTrailTS extends TestSupport.DataGeneration {
    public MixCategoryTS mixCategoryGenerator;
    
    /**
     * No arg constructor
     */    
    public RecommendedTrailTS() {
        this(new Map<String, Object>(), new List<TestSupport.TestDataField>());
    }

    /**
     * Constructor with configuration options
     * @param options 
     */    
    public RecommendedTrailTS(Map<String, Object> options) {
        this(options, new List<TestSupport.TestDataField>());
    }

    /**
     * Constructor with custom field specs
     * @param fieldSpecs 
     */    
    public RecommendedTrailTS(List<TestSupport.TestDataField> fieldSpecs) {
        this(new Map<String, Object>(), fieldSpecs);
    }

    /**
     * Constructor with configuration options and custom field specs
     * @param options 
     * @param fieldSpecs 
     */    
    public RecommendedTrailTS(Map<String, Object> options, List<TestSupport.TestDataField> fieldSpecs) {
        super(options, fieldSpecs);
        this.SOBJECT_TYPE = 'Recommended_Trail__c';
        this.generateMasterRecords = Boolean.valueOf(options.get('generateMasterRecords') ?? true);
    }

    protected override Map<Schema.SObjectField, TestSupport.TestDataField> loadDefaultSpecsByField() {
        return new Map<Schema.SObjectField, TestSupport.TestDataField>{
            Recommended_Trail__c.TrailAPIName__c => new CounterSuffixField(Recommended_Trail__c.TrailAPIName__c, 'Test_Trail_'),
            Recommended_Trail__c.TrailName__c => new CounterSuffixField(Recommended_Trail__c.TrailName__c, 'Test Trail '),
            Recommended_Trail__c.Description__c => new TestSupport.TestDataField(Recommended_Trail__c.Description__c, 'Test description.'),
            Recommended_Trail__c.Icon__c => new TestSupport.TestDataField(Recommended_Trail__c.Icon__c, 'www.testicon.com'),
            Recommended_Trail__c.Level__c => new RandomPicklistValueField(Recommended_Trail__c.Level__c),
            Recommended_Trail__c.Products__c => new TestSupport.TestDataField(Recommended_Trail__c.Products__c, 'Test products'),
            Recommended_Trail__c.URL__c => new TestSupport.TestDataField(Recommended_Trail__c.URL__c, 'www.test.com')
        };
    }

    protected override Map<Schema.SObjectField, RelationshipField> loadMasterDetailFields() {
        this.mixCategoryGenerator = new MixCategoryTS(new Map<String, Object>{'numberToGenerate' => 100});
        return new Map<Schema.SObjectField, RelationshipField> {
            Recommended_Trail__c.Mix_Category__c => new RelationshipField(
                Recommended_Trail__c.Mix_Category__c, 
                new Map<Id, sObject>(this.mixCategoryGenerator.generate()).keySet()
            )
        };
    }
}