Core/main/default/objects/Mix_Category__c/Mix_Category__c.object-meta.xml
<CustomObject>
    <label>Mix Category</label>
    <nameField>
        <label>Mix Category</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mix Categories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Core/objects/Mix_Category__c/fields/Recommended_Badge_Mix__c.field-meta.xml
<CustomField>
    <fullName>Recommended_Badge_Mix__c</fullName>
    <label>Recommended Badge Mix</label>
    <referenceTo>Recommended_Badge_Mix__c</referenceTo>
    <relationshipLabel>Mix Categories</relationshipLabel>
    <relationshipName>Mix_Categories</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Core/objects/Recommended_Badge__c/Recommended_Badge__c.object-meta.xml
<CustomObject>
    <description>Recommended Trailhead badge.</description>
    <label>Recommended Badge</label>
    <nameField>
        <displayFormat>RB-{0000000}</displayFormat>
        <label>Recommended Badge Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Recommended Badges</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Core/objects/Recommended_Badge__c/fields/HyperlinkedName__c.field-meta.xml
<CustomField>
    <fullName>HyperlinkedName__c</fullName>
    <formula>HYPERLINK(URL__c, Badge_Name__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Hyperlinked Name</label>
    <type>Text</type>
</CustomField>

Core/objects/Recommended_Badge__c/fields/Mix_Category__c.field-meta.xml
<CustomField>
    <fullName>Mix_Category__c</fullName>
    <label>Mix Category</label>
    <referenceTo>Mix_Category__c</referenceTo>
    <relationshipLabel>Recommended Badges</relationshipLabel>
    <relationshipName>Recommended_Badges</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Recommended_Badge__c/fields/Recommended_Badge_Mix__c.field-meta.xml
<CustomField>
    <fullName>Recommended_Badge_Mix__c</fullName>
    <label>Recommended Badge Mix</label>
    <referenceTo>Recommended_Badge_Mix__c</referenceTo>
    <relationshipLabel>Recommended Badges</relationshipLabel>
    <relationshipName>Recommended_Badges</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Core/main/default/objects/Recommended_Badge_Mix__c/Recommended_Badge_Mix__c.object-meta.xml
<CustomObject>
    <label>Recommended Badge Mix</label>
    <nameField>
        <label>Mix Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Recommended Badge Mixes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Core/objects/Recommended_Badge_Mix__c/fields/Private_Mix__c.field-meta.xml
<CustomField>
    <fullName>Private_Mix__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Private Mix</label>
    <type>Checkbox</type>
</CustomField>

Core/main/default/objects/Recommended_Trail__c/Recommended_Trail__c.object-meta.xml
<CustomObject>
    <label>Recommended Trail</label>
    <nameField>
        <displayFormat>RT-{0000000}</displayFormat>
        <label>Recommended Trail Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Recommended Trails</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Core/objects/Recommended_Trail__c/fields/HyperlinkedName__c.field-meta.xml
<CustomField>
    <fullName>HyperlinkedName__c</fullName>
    <description>Hyperlink of Trail Name to URL for trail on Trailhead.</description>
    <formula>HYPERLINK( URL__c , TrailName__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Hyperlinked Name</label>
    <type>Text</type>
</CustomField>

Core/objects/Recommended_Trail__c/fields/Mix_Category__c.field-meta.xml
<CustomField>
    <fullName>Mix_Category__c</fullName>
    <label>Mix Category</label>
    <referenceTo>Mix_Category__c</referenceTo>
    <relationshipLabel>Recommended Trails</relationshipLabel>
    <relationshipName>Recommended_Trails</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Recommended_Trail__c/fields/Recommended_Badge_Mix__c.field-meta.xml
<CustomField>
    <fullName>Recommended_Badge_Mix__c</fullName>
    <label>Recommended Badge Mix</label>
    <referenceTo>Recommended_Badge_Mix__c</referenceTo>
    <relationshipLabel>Recommended Trails</relationshipLabel>
    <relationshipName>Recommended_Trails</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Core/classes/selectors/MixCategoriesSelector.cls
/**
 * Selector class for Mix Category custom object.
 * @author Ben Learn
 * @since 02-16-2023
 * @group Core
 */
public inherited sharing class MixCategoriesSelector extends ApplicationSelector {
    /**
     * fflib method to hold the fields to always be queried by the selector
     * @return  `List<Schema.SObjectField>`
     */
    public List<Schema.SObjectField> getSObjectFieldList() {
        return new List<Schema.SObjectField> {
            Mix_Category__c.Id,
            Mix_Category__c.Name
        };
    }
    
    /**
     * fflib method to return the sObjectType of the object being queried
     * @return  `Schema.SObjectType`
     */
    public Schema.SObjectType getSObjectType() {
        return Mix_Category__c.sObjectType;
    }

    /**
     * Selector method to return Mix Category and parent Recommended Badge Mix Name for provided mixCategoryIds.
     * @param mixCategoryIds 
     * @return  `List<Mix_Category__c>`
     */    
    public List<Mix_Category__c> selectByIdWithRecommendedBadgeMixNames(Set<Id> mixCategoryIds) {
        fflib_QueryFactory mixCategoriesQueryFactory = newQueryFactory();

        new RecommendedBadgeMixesSelector().configureQueryFactoryFields(
            mixCategoriesQueryFactory,
            Mix_Category__c.Recommended_Badge_Mix__c.getDescribe().getRelationshipName()
        );
        
        return (List<Mix_Category__c>) Database.query(mixCategoriesQueryFactory.setCondition('Id IN :mixCategoryIds').toSOQL());
    }

    /**
     * Selector method to return Mix Category and value of Private Mix field on parent Recommended Badge Mix for provided mixCategoryIds.
     * @param mixCategoryIds 
     * @return  `List<Mix_Category__c>`
     */    
    public List<Mix_Category__c> selectByIdWithRecommendedBadgeMixPrivateMix(Set<Id> mixCategoryIds) {
        fflib_QueryFactory mixCategoriesQueryFactory = newQueryFactory();
        
        new RecommendedBadgeMixesSelector().configureQueryFactoryFields(
            mixCategoriesQueryFactory, 
            Mix_Category__c.Recommended_Badge_Mix__c.getDescribe().getRelationshipName()
        );
        
        return (List<Mix_Category__c>) Database.query(
            mixCategoriesQueryFactory.selectFieldSet(Schema.SObjectType.Mix_Category__c.fieldSets.Triggers, true).
            setCondition('Id IN :mixCategoryIds').
            toSOQL()
        );
    }

    /**
     * Selector method to return all Mix Category records (including fields from psecified field set) that are related to either a public Recommended Badge Mix or a private
     * Recommended Badge Mix owned by the running user.
     * @param fieldSet 
     * @return  `List<Mix_Category__c>`
     */    
    public List<Mix_Category__c> selectAllWithRecommendedBadgeMixInfos(Schema.FieldSet fieldSet) {
        fflib_QueryFactory mixCategoriesQueryFactory = newQueryFactory();
        new RecommendedBadgeMixesSelector().configureQueryFactoryFields(mixCategoriesQueryFactory, Mix_Category__c.Recommended_Badge_Mix__c.getDescribe().getRelationshipName());

        if(fieldSet != null) {
            mixCategoriesQueryFactory.selectFieldSet(fieldSet, true);
        }
        
        return (List<Mix_Category__c>) Database.query(
            mixCategoriesQueryFactory
            .setCondition(
                'Recommended_Badge_Mix__r.Private_Mix__c = false OR (Recommended_Badge_Mix__r.Private_Mix__c = true AND Recommended_Badge_Mix__r.OwnerId = \'' + 
                UserInfo.getUserId() + 
                '\')'
            )
            .toSOQL()
        );
    }

    /**
     * Selector method to return all Mix Category records related to a non-private Recommended Badge Mix, along with children Recommended Badges and Recommended Trails, as well
     * as parent Recommended Badge Mix information.
     * @return  `List<Mix_Category__c>`
     */    
    public List<Mix_Category__c> selectRecommendedBadgesAndTrails() {
        fflib_QueryFactory mixCategoriesQueryFactory = newQueryFactory();
        fflib_QueryFactory recommendedBadgesQueryFactory;
        fflib_QueryFactory recommendedTrailsQueryFactory;

        List<Schema.ChildRelationship> mixCategoriesChildRelationships = Schema.SObjectType.Mix_Category__c.getChildRelationships();
        for(Schema.ChildRelationship childRelationship : mixCategoriesChildRelationships) {
            if(childRelationship.getChildSObject() == Recommended_Badge__c.sObjectType) {
                recommendedBadgesQueryFactory = new RecommendedBadgesSelector().
                    addQueryFactorySubselect(mixCategoriesQueryFactory, childRelationship.getRelationshipName(), true).
                    selectFieldSet(Schema.SObjectType.Recommended_Badge__c.fieldSets.RecommendedBadgeMix, true).
                    selectField('HyperlinkedName__c');
            } else if(childRelationship.getChildSObject() == Recommended_Trail__c.sObjectType) {
                recommendedTrailsQueryFactory = new RecommendedTrailsSelector().
                    addQueryFactorySubselect(mixCategoriesQueryFactory, childRelationship.getRelationshipName(), true).
                    selectFieldSet(Schema.SObjectType.Recommended_Trail__c.fieldSets.RecommendedBadgeMix, true).
                    selectField('HyperlinkedName__c'); 
            }
        }

        new RecommendedBadgeMixesSelector().configureQueryFactoryFields(
            mixCategoriesQueryFactory, 
            Mix_Category__c.Recommended_Badge_Mix__c.getDescribe().getRelationshipName()
        );

        return (List<Mix_Category__c>) Database.query(
            mixCategoriesQueryFactory.selectFieldSet(Schema.SObjectType.Mix_Category__c.fieldSets.RecommendedBadgeMix).
            setCondition('Recommended_Badge_Mix__r.Private_Mix__c = false').toSOQL()
        );
    }
}    