Core/main/default/objects/Mix_Category__c/Mix_Category__c.object-meta.xml
<CustomObject>
    <label>Mix Category</label>
    <nameField>
        <label>Mix Category</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mix Categories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Core/objects/Mix_Category__c/fields/Recommended_Badge_Mix__c.field-meta.xml
<CustomField>
    <fullName>Recommended_Badge_Mix__c</fullName>
    <label>Recommended Badge Mix</label>
    <referenceTo>Recommended_Badge_Mix__c</referenceTo>
    <relationshipLabel>Mix Categories</relationshipLabel>
    <relationshipName>Mix_Categories</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Core/main/default/objects/Recommended_Badge_Mix__c/Recommended_Badge_Mix__c.object-meta.xml
<CustomObject>
    <label>Recommended Badge Mix</label>
    <nameField>
        <label>Mix Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Recommended Badge Mixes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Core/main/default/objects/Recommended_Trail__c/Recommended_Trail__c.object-meta.xml
<CustomObject>
    <label>Recommended Trail</label>
    <nameField>
        <displayFormat>RT-{0000000}</displayFormat>
        <label>Recommended Trail Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Recommended Trails</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Core/objects/Recommended_Trail__c/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <description>Value of the trailheadapp__Level__c field on corresponding trailheadapp__Trail__c.</description>
    <label>Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Level</valueSetName>
    </valueSet>
</CustomField>

Core/objects/Recommended_Trail__c/fields/Mix_Category__c.field-meta.xml
<CustomField>
    <fullName>Mix_Category__c</fullName>
    <label>Mix Category</label>
    <referenceTo>Mix_Category__c</referenceTo>
    <relationshipLabel>Recommended Trails</relationshipLabel>
    <relationshipName>Recommended_Trails</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Recommended_Trail__c/fields/Recommended_Badge_Mix__c.field-meta.xml
<CustomField>
    <fullName>Recommended_Badge_Mix__c</fullName>
    <label>Recommended Badge Mix</label>
    <referenceTo>Recommended_Badge_Mix__c</referenceTo>
    <relationshipLabel>Recommended Trails</relationshipLabel>
    <relationshipName>Recommended_Trails</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Core/objects/Recommended_Trail__c/fields/TrailAPIName__c.field-meta.xml
<CustomField>
    <fullName>TrailAPIName__c</fullName>
    <description>Value of the trailheadapp__API_Name__c field on the corresponding trailheadapp__Trail__c record.</description>
    <label>Trail API Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

Core/globalValueSets/Level.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Beginner</fullName>
        <default>true</default>
        <label>Beginner</label>
    </customValue>
    <customValue>
        <fullName>Intermediate</fullName>
    </customValue>
    <customValue>
        <fullName>Advanced</fullName>
    </customValue>
    <customValue>
        <fullName>Superbadge Unit</fullName>
    </customValue>
    <customValue>
        <fullName>Superbadge</fullName>
    </customValue>
    <customValue>
        <fullName>Super Set</fullName>
    </customValue>
    <masterLabel>Level</masterLabel>
</GlobalValueSet>

Core/classes/tests/RecommendedTrailsSelectorTests.cls
/**
 * @description       : Test class for RecommendedTrailsSelector.
 * @author            : Ben Learn
 * @last modified on  : 02-20-2023
 * @last modified by  : Ben Learn
**/
@isTest
private class RecommendedTrailsSelectorTests {
    @isTest
    private static void getSObjectFieldList_test() {
        List<Schema.SObjectField> expectedFieldList = new List<Schema.SObjectField> {
            Recommended_Trail__c.Id,
            Recommended_Trail__c.Level__c
        };

        Assert.areEqual(expectedFieldList, new RecommendedTrailsSelector().getSObjectFieldList(), SelectorTestErrorMessages.SOBJECT_FIELD_LIST_ERROR_MESSAGE);
    }

    @isTest
    private static void getSObjectType_test() {
        Assert.areEqual(Recommended_Trail__c.sObjectType, new RecommendedTrailsSelector().getSObjectType(), SelectorTestErrorMessages.SOBJECT_TYPE_ERROR_MESSAGE);
    }

    @isTest
    private static void selectTrailAPINameById_test() {
        RecommendedBadgeMixTS badgeMixGenerator = new RecommendedBadgeMixTS(new Map<String, Object>{'numberToGenerate' => 1, 'generateRecordIDs' => false});
        insert badgeMixGenerator.generate();
        MixCategoryTS mixCategoryGenerator = new MixCategoryTS(
            new Map<String, Object>{'numberToGenerate' => 10, 'generateMasterRecords' => false, 'generateRecordIDs' => false},
            new List<TestSupport.TestDataField>{new RelationshipField(Mix_Category__c.Recommended_Badge_Mix__c, (new Map<Id, sObject>(badgeMixGenerator.records)).keySet())}
        );
        insert mixCategoryGenerator.generate();
        RecommendedTrailTS recommendedTrailGenerator = new RecommendedTrailTS(
            new Map<String, Object>{'generateMasterRecords' => false, 'generateRecordIDs' => false},
            new List<TestSupport.TestDataField>{new RelationshipField(Recommended_Trail__c.Mix_Category__c, (new Map<Id, sObject>(mixCategoryGenerator.records)).keySet())}
        );
        insert recommendedTrailGenerator.generate();

        Recommended_Trail__c expectedTrail = [SELECT Id, TrailAPIName__c FROM Recommended_Trail__c LIMIT 1];

        Test.startTest();
        String trailAPIName = new RecommendedTrailsSelector().selectTrailAPINameById(expectedTrail.Id).TrailAPIName__c;
        Test.stopTest();

        Assert.areEqual(expectedTrail.TrailAPIName__c, trailAPIName, 'Expected Trail API Name of corresponding Recommended Trail to be returned.');
    }
}