Core/main/default/objects/Mix_Category__c/Mix_Category__c.object-meta.xml
<CustomObject>
    <label>Mix Category</label>
    <nameField>
        <label>Mix Category</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mix Categories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Core/objects/Mix_Category__c/fields/Recommended_Badge_Mix__c.field-meta.xml
<CustomField>
    <fullName>Recommended_Badge_Mix__c</fullName>
    <label>Recommended Badge Mix</label>
    <referenceTo>Recommended_Badge_Mix__c</referenceTo>
    <relationshipLabel>Mix Categories</relationshipLabel>
    <relationshipName>Mix_Categories</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Core/objects/Recommended_Badge__c/Recommended_Badge__c.object-meta.xml
<CustomObject>
    <description>Recommended Trailhead badge.</description>
    <label>Recommended Badge</label>
    <nameField>
        <displayFormat>RB-{0000000}</displayFormat>
        <label>Recommended Badge Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Recommended Badges</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Core/objects/Recommended_Badge__c/fields/BadgeAPIName__c.field-meta.xml
<CustomField>
    <fullName>BadgeAPIName__c</fullName>
    <label>Badge API Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

Core/objects/Recommended_Badge__c/fields/High_Priority__c.field-meta.xml
<CustomField>
    <fullName>High_Priority__c</fullName>
    <defaultValue>false</defaultValue>
    <label>High Priority</label>
    <type>Checkbox</type>
</CustomField>

Core/main/default/objects/Recommended_Badge__c/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <label>Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Beginner</fullName>
                <default>true</default>
                <label>Beginner</label>
            </value>
            <value>
                <fullName>Intermediate</fullName>
            </value>
            <value>
                <fullName>Advanced</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Core/objects/Recommended_Badge__c/fields/Mix_Category__c.field-meta.xml
<CustomField>
    <fullName>Mix_Category__c</fullName>
    <label>Mix Category</label>
    <referenceTo>Mix_Category__c</referenceTo>
    <relationshipLabel>Recommended Badges</relationshipLabel>
    <relationshipName>Recommended_Badges</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Recommended_Badge__c/fields/Recommended_Badge_Mix__c.field-meta.xml
<CustomField>
    <fullName>Recommended_Badge_Mix__c</fullName>
    <label>Recommended Badge Mix</label>
    <referenceTo>Recommended_Badge_Mix__c</referenceTo>
    <relationshipLabel>Recommended Badges</relationshipLabel>
    <relationshipName>Recommended_Badges</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Core/objects/Recommended_Badge__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Value of trailheadapp__Type__c field on corresponding trailheadapp__Badge__c.</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Module</fullName>
                <default>true</default>
                <label>Module</label>
            </value>
            <value>
                <fullName>Project</fullName>
            </value>
            <value>
                <fullName>Superbadge</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Core/main/default/objects/Recommended_Badge_Mix__c/Recommended_Badge_Mix__c.object-meta.xml
<CustomObject>
    <label>Recommended Badge Mix</label>
    <nameField>
        <label>Mix Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Recommended Badge Mixes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Core/objects/Recommended_Badge_Mix__c/fields/Private_Mix__c.field-meta.xml
<CustomField>
    <fullName>Private_Mix__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Private Mix</label>
    <type>Checkbox</type>
</CustomField>

Core/classes/tests/RecommendedBadgesSelectorTests.cls
@isTest(IsParallel=true)
private class RecommendedBadgesSelectorTests {
    @isTest
    private static void getSObjectFieldList_test() {
        List<Schema.SObjectField> expectedFieldList = new List<Schema.SObjectField> {
            Recommended_Badge__c.Id,
            Recommended_Badge__c.Level__c,
            Recommended_Badge__c.Type__c
        };

        Assert.areEqual(expectedFieldList, new RecommendedBadgesSelector(false, fflib_SObjectSelector.DataAccess.LEGACY).getSObjectFieldList(), 'Expected prescribed field list.');
    }

    @isTest
    private static void getSObjectType_test() {
        Assert.areEqual(Recommended_Badge__c.sObjectType, new RecommendedBadgesSelector().getSObjectType(), 'Expected prescribed sObjectType.');
    }

    private static List<Recommended_Badge__c> generateData(Boolean returnRecommendedBadges) {
        RecommendedBadgeMixTS badgeMixGenerator = new RecommendedBadgeMixTS(new Map<String, Object>{'generateRecordIDs' => false, 'numberToGenerate' => 10});
        List<Recommended_Badge_Mix__c> badgeMixes = (List<Recommended_Badge_Mix__c>) badgeMixGenerator.generate();
        insert badgeMixes;

        MixCategoryTS mixCategoryGenerator = new MixCategoryTS(
            new Map<String, Object>{'generateRecordIDs' => false, 'numberToGenerate' => 4},
            new List<TestSupport.TestDataField>{new RelationshipField(Mix_Category__c.Recommended_Badge_Mix__c, (new Map<Id, Recommended_Badge_Mix__c>(badgeMixes)).keySet())}
        );
        List<Mix_Category__c> mixCategories = (List<Mix_Category__c>) mixCategoryGenerator.generate();
        insert mixCategories;

        RecommendedBadgeTS badgeGenerator = new RecommendedBadgeTS(
            new Map<String, Object>{'generateRecordIDs' => false}, 
            new List<TestSupport.TestDataField>{
                new BooleanField(Recommended_Badge__c.High_Priority__c, true),
                new RelationshipField(Recommended_Badge__c.Mix_Category__c, (new Map<Id, Mix_Category__c>(mixCategories)).keySet())}
        );
        List<Recommended_Badge__c> badges = (List<Recommended_Badge__c>) badgeGenerator.generate();
        insert badges;
        return badges;
    }

    @isTest
    private static void selectedAllRelatedToUserPrivateMix_test() {
        generateData(false);
        Map<Id, Recommended_Badge__c> expectedRecommendedBadgesById = new Map<Id, Recommended_Badge__c>([
            SELECT Id FROM Recommended_Badge__c WHERE Mix_Category__r.Recommended_Badge_Mix__r.Private_Mix__c = true
        ]);
        Map<Id, Recommended_Badge__c> resultRecommendedBadgesById = new Map<Id, Recommended_Badge__c>(
            new RecommendedBadgesSelector().selectedAllRelatedToUserPrivateMix()
        );
        Assert.areEqual(
            expectedRecommendedBadgesById.keySet(), 
            resultRecommendedBadgesById.keySet(), 
            'Expected only Recommended Badges related to private Recommended Badge Mixes to be returned.'
        );
    }

    @isTest
    private static void selectBadgeAPINameById_test() {
        generateData(false);
        Recommended_Badge__c expectedBadge = [SELECT Id, BadgeAPIName__c FROM Recommended_Badge__c LIMIT 1];
        Assert.areEqual(
            expectedBadge.BadgeAPIName__c, 
            new RecommendedBadgesSelector().selectBadgeAPINameById(expectedBadge.Id).BadgeAPIName__c,
            'Expected Badge API Name of corresponding Recommended Badge to be returned.'
        );
    }

    @isTest
    private static void selectBadgesByAPINames_test() {
        List<Recommended_Badge__c> testBadges = generateData(true);
        Map<Id, String> selectorBadgeAPINamesByID = new Map<Id, String>();
        Integer selectedIndex;
        for(Integer i = 0; i < 10; i++) {
            selectedIndex = Integer.valueOf(Math.floor(Math.random() * testBadges.size()));
            selectorBadgeAPINamesByID.put(testBadges[selectedIndex].Id, testBadges[selectedIndex].BadgeAPIName__c);
        }

        Test.startTest();
        Map<Id, Recommended_Badge__c> resultBadges = new Map<Id, Recommended_Badge__c>(
            new RecommendedBadgesSelector().selectBadgesByAPINames(new Set<String>(selectorBadgeAPINamesByID.values()))
        );
        Test.stopTest();

        Assert.areEqual(selectorBadgeAPINamesByID.keySet(), resultBadges.keySet(), 'Expected Recommended Badges with provided API names to be returned.');
    }
}