Core/objects/Recommended_Badge__c/Recommended_Badge__c.object-meta.xml
<CustomObject>
    <description>Recommended Trailhead badge.</description>
    <label>Recommended Badge</label>
    <nameField>
        <displayFormat>RB-{0000000}</displayFormat>
        <label>Recommended Badge Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Recommended Badges</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Core/objects/Recommended_Badge__c/fields/Badge__c.field-meta.xml
<CustomField>
    <fullName>Badge__c</fullName>
    <label>Badge</label>
    <referenceTo>trailheadapp__Badge__c</referenceTo>
    <relationshipLabel>Recommended Badges</relationshipLabel>
    <relationshipName>Recommended_Badges</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Core/main/default/objects/Recommended_Trail__c/Recommended_Trail__c.object-meta.xml
<CustomObject>
    <label>Recommended Trail</label>
    <nameField>
        <displayFormat>RT-{0000000}</displayFormat>
        <label>Recommended Trail Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Recommended Trails</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Core/objects/Recommended_Trail__c/fields/Trail__c.field-meta.xml
<CustomField>
    <fullName>Trail__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Trail</label>
    <referenceTo>trailheadapp__Trail__c</referenceTo>
    <relationshipLabel>Recommended Trails</relationshipLabel>
    <relationshipName>Recommended_Trails</relationshipName>
    <type>Lookup</type>
</CustomField>

Core/classes/TrailheadEntityFormController.cls
/**
 * Apex controller for trailheadEntityForm LWC.
 * @author Ben Learn
 * @since 06-08-2024
 * @group Core
**/
public with sharing class TrailheadEntityFormController {
    /**
     * Returns all the names and API names of all non-archived Badges (when childEntityType is Recommended_Badge__c) or Trails
     * (when childEntityType is Recommended_Trail__c) through a SOQL query using the standard Salesforce REST API on Trail Tracker Provider.
     * @param childEntityType 
     * @return  `Map<String, Object>`
     */
    @AuraEnabled(cacheable=true)
    public static Map<String, Object> getTrailheadEntitiesByAPIName(String childEntityType) {
        if(childEntityType != null) {
            String query = 'SELECT trailheadapp__API_Name__c, Name FROM trailheadapp__';
            switch on (childEntityType) {
                when 'Recommended_Badge__c' {
                    query += 'Badge__c';
                } when 'Recommended_Trail__c' {
                    query += 'Trail__c';
                }
            }
            query += ' WHERE trailheadapp__Archived__c = false';
            HttpRequest request = new HttpRequest();
            request.setEndpoint('callout:Provider_Scratch/services/data/v60.0/query/?q=' + EncodingUtil.urlEncode(query, 'UTF-8'));
            request.setMethod('GET');
            HttpResponse response = new Http().send(request);
            return (Map<String, Object>) JSON.deserializeUntyped(response.getBody());
        }
        return null;
    }
}