force-app/main/default/objects/Mix_Category__c/Mix_Category__c.object-meta.xml
<CustomObject>
    <label>Mix Category</label>
    <nameField>
        <label>Mix Category</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mix Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Mix_Category__c/fields/Recommended_Badge_Mix__c.field-meta.xml
<CustomField>
    <fullName>Recommended_Badge_Mix__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Recommended Badge Mix</label>
    <referenceTo>Recommended_Badge_Mix__c</referenceTo>
    <relationshipLabel>Mix Categories</relationshipLabel>
    <relationshipName>Mix_Categories</relationshipName>
    <type>Lookup</type>
</CustomField>

DataModel/main/default/objects/Recommended_Badge__c/Recommended_Badge__c.object-meta.xml
<CustomObject>
    <label>Recommended Badge</label>
    <nameField>
        <displayFormat>RB-{0000000}</displayFormat>
        <label>Recommended Badge Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Recommended Badges</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Core/objects/Recommended_Badge__c/fields/Badge_Mix_Key__c.field-meta.xml
<CustomField>
    <fullName>Badge_Mix_Key__c</fullName>
    <label>Badge Mix Key</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Core/objects/Recommended_Badge__c/fields/BadgeAPIName__c.field-meta.xml
<CustomField>
    <fullName>BadgeAPIName__c</fullName>
    <label>Badge API Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

DataModel/main/default/objects/Recommended_Badge__c/fields/High_Priority__c.field-meta.xml
<CustomField>
    <fullName>High_Priority__c</fullName>
    <defaultValue>false</defaultValue>
    <label>High Priority</label>
    <type>Checkbox</type>
</CustomField>

Core/objects/Recommended_Badge__c/fields/Hours_Estimate__c.field-meta.xml
<CustomField>
    <fullName>Hours_Estimate__c</fullName>
    <label>Hours Estimate</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Core/main/default/objects/Recommended_Badge__c/fields/Minutes_Estimate__c.field-meta.xml
<CustomField>
    <fullName>Minutes_Estimate__c</fullName>
    <label>Minutes Estimate</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Recommended_Badge__c/fields/Mix_Category__c.field-meta.xml
<CustomField>
    <fullName>Mix_Category__c</fullName>
    <label>Mix Category</label>
    <referenceTo>Mix_Category__c</referenceTo>
    <relationshipLabel>Recommended Badges</relationshipLabel>
    <relationshipName>Recommended_Badges</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Recommended_Badge__c/fields/Recommended_Badge_Mix__c.field-meta.xml
<CustomField>
    <fullName>Recommended_Badge_Mix__c</fullName>
    <label>Recommended Badge Mix</label>
    <referenceTo>Recommended_Badge_Mix__c</referenceTo>
    <relationshipLabel>Recommended Badges</relationshipLabel>
    <relationshipName>Recommended_Badges</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Recommended_Badge_Mix__c/Recommended_Badge_Mix__c.object-meta.xml
<CustomObject>
    <label>Recommended Badge Mix</label>
    <nameField>
        <label>Mix Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Recommended Badge Mixes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

DataModel/main/default/objects/Recommended_Badge_Mix__c/fields/Private_Mix__c.field-meta.xml
<CustomField>
    <fullName>Private_Mix__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Private Mix</label>
    <type>Checkbox</type>
</CustomField>

Triggers/classes/RecommendedBadgeTriggerHandler.cls
/**
 * Trigger handler for Recommended_Badge__c object
 * @author Ben Learn
 * @since 06-10-2024
 * @group Triggers
 */
public without sharing class RecommendedBadgeTriggerHandler extends TriggerHandler {
    /**
     * Constructor for trigger handler
     */    
    public RecommendedBadgeTriggerHandler() {
        super();
    }

    protected override void beforeInsert(List<sObject> newRecords) {
        RecommendedBadgeTrailTriggerHelper.updateURLPaths(Recommended_Badge__c.getSObjectType(), newRecords, null);
        populateBadgeMixKeys((List<Recommended_Badge__c>) newRecords, null);
    }

    protected override void afterInsert(Map<Id, sObject> newRecordsMap) {
        RecommendedBadgeTrailTriggerHelper.queueTrailTrackerProviderCallouts(Recommended_Badge__c.getSObjectType(), newRecordsMap);
    }

    protected override void beforeUpdate(Map<Id, sObject> updatedRecordsMap, Map<Id, sObject> oldRecordsMap) {
        RecommendedBadgeTrailTriggerHelper.updateURLPaths(Recommended_Badge__c.getSObjectType(), updatedRecordsMap.values(), oldRecordsMap);
        clearTimeEstimatesAndHighPriority((List<Recommended_Badge__c>) updatedRecordsMap.values(), (Map<Id, Recommended_Badge__c>) oldRecordsMap);
        populateBadgeMixKeys((List<Recommended_Badge__c>) updatedRecordsMap.values(), (Map<Id, Recommended_Badge__c>) oldRecordsMap);
    }

    /**
     * Method to populate unique key in the format [Badge API Name]-[Recommended Badge Mix Name].
     * Done to ensure that there aren't any duplicated recommended badges within the same recommended badge mix.
     * @param newRecommendedBadges 
     * @param oldRecommendedBadgeMap 
     */    
    private static void populateBadgeMixKeys(List<Recommended_Badge__c> newRecommendedBadges, Map<Id, Recommended_Badge__c> oldRecommendedBadgeMap) {
        Set<Id> mixCategoryIds = new Set<Id>();

        for(Recommended_Badge__c newRecommendedBadge : newRecommendedBadges) {
            if(
                (newRecommendedBadge.Badge_Mix_Key__c == null) || 
                (oldRecommendedBadgeMap?.get(newRecommendedBadge.Id).Mix_Category__c != newRecommendedBadge.Mix_Category__c)
            ) {
                mixCategoryIds.add(newRecommendedBadge.Mix_Category__c);
            }
        }

        Map<Id, Mix_Category__c> mixCategoryMap = new Map<Id, Mix_Category__c>(new MixCategoriesSelector().selectByIdWithRecommendedBadgeMixNames(mixCategoryIds));
        for(Recommended_Badge__c newRecommendedBadge : newRecommendedBadges) {
            if(
                (newRecommendedBadge.Badge_Mix_Key__c == null) || 
                (oldRecommendedBadgeMap?.get(newRecommendedBadge.Id).Mix_Category__c != newRecommendedBadge.Mix_Category__c)
            ){
                String recommendedBadgeMixName = mixCategoryMap.get(newRecommendedBadge.Mix_Category__c).Recommended_Badge_Mix__r.Name;
                newRecommendedBadge.Badge_Mix_Key__c = newRecommendedBadge.BadgeAPIName__c + '-' + recommendedBadgeMixName;
            }
        }
    }

    private static void clearTimeEstimatesAndHighPriority(List<Recommended_Badge__c> newRecommendedBadges, Map<Id, Recommended_Badge__c> oldRecommendedBadgeMap) {
        Set<Id> newMixCategoryIds = new Set<Id>();
        Set<Id> oldMixCategoryIds = new Set<Id>();
        for(Recommended_Badge__c newRecommendedBadge : newRecommendedBadges) {
            if(newRecommendedBadge.Mix_Category__c != oldRecommendedBadgeMap.get(newRecommendedBadge.Id).Mix_Category__c) {
                newMixCategoryIds.add(newRecommendedBadge.Mix_Category__c);
                oldMixCategoryIds.add(oldRecommendedBadgeMap.get(newRecommendedBadge.Id).Mix_Category__c);
            }
        }

        if((newMixCategoryIds.size() > 0) && (oldMixCategoryIds.size() > 0)) {
            Map<Id, Mix_Category__c> oldMixCategoryMap = new Map<Id, Mix_Category__c>(new MixCategoriesSelector().selectByIdWithRecommendedBadgeMixPrivateMix(oldMixCategoryIds));
            Map<Id, Mix_Category__c> newMixCategoryMap = new Map<Id, Mix_CategorY__c>(new MixCategoriesSelector().selectByIdWithRecommendedBadgeMixPrivateMix(newMixCategoryIds));
    
            for(Recommended_Badge__c newRecommendedBadge : newRecommendedBadges) {
                if(
                    (newRecommendedBadge.Mix_Category__c != oldRecommendedBadgeMap.get(newRecommendedBadge.Id).Mix_Category__c) && 
                    !newMixCategoryMap.get(newRecommendedBadge.Mix_Category__c).Recommended_Badge_Mix__r.Private_Mix__c && 
                    oldMixCategoryMap.get(oldRecommendedBadgeMap.get(newRecommendedBadge.Id).Mix_Category__c).Recommended_Badge_Mix__r.Private_Mix__c
                ) {
                    newRecommendedBadge.Hours_Estimate__c = null;
                    newRecommendedBadge.Minutes_Estimate__c = null;
                    newRecommendedBadge.High_Priority__c = false;
                }
            }
        }
    }
}