force-app/main/default/objects/Mix_Category__c/Mix_Category__c.object-meta.xml
<CustomObject>
    <label>Mix Category</label>
    <nameField>
        <label>Mix Category</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mix Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Mix_Category__c/fields/Recommended_Badge_Mix__c.field-meta.xml
<CustomField>
    <fullName>Recommended_Badge_Mix__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Recommended Badge Mix</label>
    <referenceTo>Recommended_Badge_Mix__c</referenceTo>
    <relationshipLabel>Mix Categories</relationshipLabel>
    <relationshipName>Mix_Categories</relationshipName>
    <type>Lookup</type>
</CustomField>

DataModel/main/default/objects/Recommended_Badge__c/Recommended_Badge__c.object-meta.xml
<CustomObject>
    <label>Recommended Badge</label>
    <nameField>
        <displayFormat>RB-{0000000}</displayFormat>
        <label>Recommended Badge Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Recommended Badges</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Core/objects/Recommended_Badge__c/fields/BadgeName__c.field-meta.xml
<CustomField>
    <fullName>BadgeName__c</fullName>
    <description>Name of the corresponding trailheadapp__Badge__c.</description>
    <label>Badge Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

DataModel/main/default/objects/Recommended_Badge__c/fields/High_Priority__c.field-meta.xml
<CustomField>
    <fullName>High_Priority__c</fullName>
    <defaultValue>false</defaultValue>
    <label>High Priority</label>
    <type>Checkbox</type>
</CustomField>

Core/objects/Recommended_Badge__c/fields/High_Priority_Id__c.field-meta.xml
<CustomField>
    <fullName>High_Priority_Id__c</fullName>
    <formula>IF(High_Priority__c, &apos;HP&apos; + Id, &apos;&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>High Priority Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Recommended_Badge__c/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <label>Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Level</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Recommended_Badge__c/fields/Mix_Category__c.field-meta.xml
<CustomField>
    <fullName>Mix_Category__c</fullName>
    <label>Mix Category</label>
    <referenceTo>Mix_Category__c</referenceTo>
    <relationshipLabel>Recommended Badges</relationshipLabel>
    <relationshipName>Recommended_Badges</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Recommended_Badge__c/fields/Recommended_Badge_Mix__c.field-meta.xml
<CustomField>
    <fullName>Recommended_Badge_Mix__c</fullName>
    <label>Recommended Badge Mix</label>
    <referenceTo>Recommended_Badge_Mix__c</referenceTo>
    <relationshipLabel>Recommended Badges</relationshipLabel>
    <relationshipName>Recommended_Badges</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Recommended_Badge__c/fields/Time_Estimate__c.field-meta.xml
<CustomField>
    <fullName>Time_Estimate__c</fullName>
    <formula>IF(TEXT(Hours_Estimate__c) != &apos;&apos;, TEXT(Hours_Estimate__c) &amp; &apos; hr &apos;, &apos;&apos;) &amp; 
IF(TEXT(Minutes_Estimate__c) != &apos;&apos;, TEXT(Minutes_Estimate__c) &amp; &apos; min&apos;, &apos;&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Time Estimate</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Recommended_Badge__c/fields/Time_Estimate_Minutes__c.field-meta.xml
<CustomField>
    <fullName>Time_Estimate_Minutes__c</fullName>
    <formula>Minutes_Estimate__c + Hours_Estimate__c * 60</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Time Estimate (Minutes)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Recommended_Badge__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Module</fullName>
                <default>true</default>
                <label>Module</label>
            </value>
            <value>
                <fullName>Project</fullName>
            </value>
            <value>
                <fullName>Superbadge</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Recommended_Badge__c/fields/URL__c.field-meta.xml
<CustomField>
    <fullName>URL__c</fullName>
    <formula>Badge__r.trailheadapp__URL__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>URL</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Recommended_Badge_Mix__c/Recommended_Badge_Mix__c.object-meta.xml
<CustomObject>
    <label>Recommended Badge Mix</label>
    <nameField>
        <label>Mix Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Recommended Badge Mixes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Recommended_Badge_Mix__c/fields/Default_Badge_Mix__c.field-meta.xml
<CustomField>
    <fullName>Default_Badge_Mix__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Default Badge Mix</label>
    <type>Checkbox</type>
</CustomField>

DataModel/main/default/objects/Recommended_Badge_Mix__c/fields/Private_Mix__c.field-meta.xml
<CustomField>
    <fullName>Private_Mix__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Private Mix</label>
    <type>Checkbox</type>
</CustomField>

unpackageable/globalValueSets/Level.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Beginner</fullName>
        <default>true</default>
        <label>Beginner</label>
    </customValue>
    <customValue>
        <fullName>Intermediate</fullName>
    </customValue>
    <customValue>
        <fullName>Advanced</fullName>
    </customValue>
    <masterLabel>Level</masterLabel>
</GlobalValueSet>

PrivateMixView/classes/PrivateViewControllerTests.cls
@isTest(IsParallel=true)
private class PrivateViewControllerTests {
    @isTest
    private static void getMixCategoryData_test() {
        RecommendedBadgeMixTS badgeMixGenerator = new RecommendedBadgeMixTS(new Map<String, Object>{
            'generateRecordIDs' => false,
            'generatorReturnValue' => 'all',
            'numberToGenerate' => 9
        });
        badgeMixGenerator.generate();
        badgeMixGenerator.numberToGenerate = 1;
        List<Recommended_Badge_Mix__c> badgeMixes = (List<Recommended_Badge_Mix__c>) badgeMixGenerator.setFieldSpec(
            new TestSupport.TestDataField(Recommended_Badge_Mix__c.Default_Badge_Mix__c, true)
        ).generate();
        insert badgeMixes;
        
        MixCategoryTS mixCategoryGenerator = new MixCategoryTS(
            new Map<String, Object>{'generateRecordIDs' => false, 'numberToGenerate' => 4},
            new List<TestSupport.TestDataField>{new RelationshipField(Mix_Category__c.Recommended_Badge_Mix__c, (new Map<Id, Recommended_Badge_Mix__c>(badgeMixes)).keySet())}
        );
        List<Mix_Category__c> mixCategories = (List<Mix_Category__c>) mixCategoryGenerator.generate();
        insert mixCategories;

        mixCategories = [
            SELECT Name, Recommended_Badge_Mix__r.Name, Recommended_Badge_Mix__r.Private_Mix__c
            FROM Mix_Category__c
            ORDER BY Name
        ];

        Test.startTest();
        List<Mix_Category__c> mixCategoryData = PrivateViewController.getMixCategoryData();
        Test.stopTest();

        System.assert(mixCategories.equals(mixCategoryData), 'Expected Mix Category data to equal test data.');
    }

    @isTest
    private static void getPrivateMixRecommendedBadges_test() {
        RecommendedBadgeMixTS badgeMixGenerator = new RecommendedBadgeMixTS(new Map<String, Object>{'generateRecordIDs' => false, 'numberToGenerate' => 2});
        List<Recommended_Badge_Mix__c> badgeMixes = (List<Recommended_Badge_Mix__c>) badgeMixGenerator.generate();
        insert badgeMixes;

        MixCategoryTS mixCategoryGenerator = new MixCategoryTS(
            new Map<String, Object>{'generateRecordIDs' => false, 'numberToGenerate' => 20},
            new List<TestSupport.TestDataField>{new RelationshipField(Mix_Category__c.Recommended_Badge_Mix__c, (new Map<Id, Recommended_Badge_Mix__c>(badgeMixes)).keySet())}
        );
        List<Mix_Category__c> mixCategories = (List<Mix_Category__c>) mixCategoryGenerator.generate();
        insert mixCategories;

        RecommendedBadgeTS badgeGenerator = new RecommendedBadgeTS(
            new Map<String, Object>{'generateRecordIDs' => false}, 
            new List<TestSupport.TestDataField>{
                new BooleanField(Recommended_Badge__c.High_Priority__c, true),
                new RelationshipField(Recommended_Badge__c.Mix_Category__c, (new Map<Id, Mix_Category__c>(mixCategories)).keySet())}
        );
        List<Recommended_Badge__c> badges = (List<Recommended_Badge__c>) badgeGenerator.generate();
        insert badges;

        List<Recommended_Badge__c> resultRecommendedBadges = [
            SELECT BadgeName__c, High_Priority__c, High_Priority_Id__c, Level__c, Time_Estimate_Minutes__c, Time_Estimate__c, Type__c, URL__c, Mix_Category__r.Name 
            FROM Recommended_Badge__c 
            WHERE Mix_Category__r.Recommended_Badge_Mix__r.Private_Mix__c = true ORDER BY BadgeName__c
        ];

        Map<String, List<Recommended_Badge__c>> resultRecommendedBadgeMap = new Map<String, List<Recommended_Badge__c>>();
        resultRecommendedBadgeMap.put('High Priority', new List<Recommended_Badge__c>());
        for(Recommended_Badge__c rb : resultRecommendedBadges) {
            if(rb.High_Priority__c) {
                List<Recommended_Badge__c> currentRecommendedBadges = resultRecommendedBadgeMap.get('High Priority');
                currentRecommendedBadges.add(rb);
                resultRecommendedBadgeMap.put('High Priority', currentRecommendedBadges);
            }

            if(resultRecommendedBadgeMap.get(rb.Mix_Category__r.Name) != null) {
                List<Recommended_Badge__c> currentRecommendedBadges = resultRecommendedBadgeMap.get(rb.Mix_Category__r.Name);
                currentRecommendedBadges.add(rb);
                resultRecommendedBadgeMap.put(rb.Mix_Category__r.Name, currentRecommendedBadges);
            } else {
                resultRecommendedBadgeMap.put(rb.Mix_Category__r.Name, new List<Recommended_Badge__c>{rb});
            }
        }

        Test.startTest();
        Map<String, List<Recommended_Badge__c>> privateViewMap = PrivateViewController.getPrivateMixRecommendedBadges();
        Test.stopTest();

        Assert.isTrue(resultRecommendedBadgeMap.keySet().equals(privateViewMap.keySet()), 'Expected private view Recommended Badges to equal test data.');
        for(String mixCategory : privateViewMap.keySet()) {
            List<Recommended_Badge__c> expectedMixCategoryBadges = resultRecommendedBadgeMap.get(mixCategory);
            for(Recommended_Badge__c badge : privateViewMap.get(mixCategory)) {
                expectedMixCategoryBadges.remove(expectedMixCategoryBadges.indexOf(badge));
            }
            Assert.areEqual(0, expectedMixCategoryBadges.size(), 'Expected private view Recommended Badges to equal test data.');
        }
    }
}