force-app/main/default/objects/Mix_Category__c/Mix_Category__c.object-meta.xml
<CustomObject>
    <label>Mix Category</label>
    <nameField>
        <label>Mix Category</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mix Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Mix_Category__c/fields/Recommended_Badge_Mix__c.field-meta.xml
<CustomField>
    <fullName>Recommended_Badge_Mix__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Recommended Badge Mix</label>
    <referenceTo>Recommended_Badge_Mix__c</referenceTo>
    <relationshipLabel>Mix Categories</relationshipLabel>
    <relationshipName>Mix_Categories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Recommended_Badge_Mix__c/Recommended_Badge_Mix__c.object-meta.xml
<CustomObject>
    <label>Recommended Badge Mix</label>
    <nameField>
        <label>Mix Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Recommended Badge Mixes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/BensViewService.cls
/**
 * @description       : Apex controller for bensViewContainer LWC.
 * @author            : Ben Learn
 * @group             : 
 * @last modified on  : 03-05-2022
 * @last modified by  : Ben Learn
**/
public with sharing class BensViewService {
    @AuraEnabled(cacheable=true)
    public static List<String> getBensMixCategoryNames() {
        List<Mix_Category__c> bensMixCategories = [SELECT Name FROM Mix_Category__c WHERE Recommended_Badge_Mix__r.Name LIKE 'Ben%'
            ORDER BY Name];

        List<String> bensMixCategoryNames = new List<String>();
        for(Mix_Category__c mc : bensMixCategories) {
            bensMixCategoryNames.add(mc.Name);
        }

        return bensMixCategoryNames;
    }
}