force-app/main/default/objects/Mix_Category__c/Mix_Category__c.object-meta.xml
<CustomObject>
    <label>Mix Category</label>
    <nameField>
        <label>Mix Category</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mix Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

DataModel/main/default/objects/Recommended_Badge__c/Recommended_Badge__c.object-meta.xml
<CustomObject>
    <label>Recommended Badge</label>
    <nameField>
        <displayFormat>RB-{0000000}</displayFormat>
        <label>Recommended Badge Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Recommended Badges</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

DataModel/main/default/objects/Recommended_Badge__c/fields/High_Priority__c.field-meta.xml
<CustomField>
    <fullName>High_Priority__c</fullName>
    <defaultValue>false</defaultValue>
    <label>High Priority</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Recommended_Badge__c/fields/Mix_Category__c.field-meta.xml
<CustomField>
    <fullName>Mix_Category__c</fullName>
    <label>Mix Category</label>
    <referenceTo>Mix_Category__c</referenceTo>
    <relationshipLabel>Recommended Badges</relationshipLabel>
    <relationshipName>Recommended_Badges</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

PrivateMixView/main/default/classes/PrivateViewController.cls
/**
 * @description       : Apex controller for privateViewContainer LWC.
 * @author            : Ben Learn
 * @last modified on  : 01-29-2023
 * @last modified by  : Ben Learn
**/
public with sharing class PrivateViewController {

    /**
    * @description Method to retrieve names of mix categories, names of parent Recommended Badge Mixes, and privacy status of parent Recommended Badge Mixes.
    * @author Ben Learn | 03-11-2022 
    * @return List<Mix_Category__c> 
    **/
    @AuraEnabled(cacheable=true)
    public static List<Mix_Category__c> getMixCategoryData() {
        List<Mix_Category__c> mixCategoryData = new MixCategoriesSelector().selectAllWithRecommendedBadgeMixInfos(Schema.SObjectType.Mix_Category__c.fieldSets.PrivateMixView);
        return mixCategoryData;
    }

    /**
    * @description Method to retrieve recommended badges for personal recommended badge mix.
    * @author Ben Learn | 03-11-2022 
    * @return Map<String, List<Recommended_Badge__c>> 
    **/
    @AuraEnabled
    public static Map<String, List<Recommended_Badge__c>> getPrivateMixRecommendedBadges() {
        List<Recommended_Badge__c> privateMixRecommendedBadges = new RecommendedBadgesSelector().selectAllRelatedToPrivateRecommendedBadgeMixes();
        Map<String, List<Recommended_Badge__c>> privateViewMap = new Map<String, List<Recommended_Badge__c>>();
        privateViewMap.put('High Priority', new List<Recommended_Badge__c>());

        List<Recommended_Badge__c> tempRecommendedBadges = new List<Recommended_Badge__c>();

        for(Recommended_Badge__c rb : privateMixRecommendedBadges) {
            if(rb.High_Priority__c) {
                tempRecommendedBadges = privateViewMap.get('High Priority');
                tempRecommendedBadges.add(rb);
                privateViewMap.put('High Priority', tempRecommendedBadges);
            }

            if(privateViewMap.get(rb.Mix_Category__r.Name) != null) {
                tempRecommendedBadges = privateViewMap.get(rb.Mix_Category__r.Name);
                tempRecommendedBadges.add(rb);
                privateViewMap.put(rb.Mix_Category__r.Name, tempRecommendedBadges);
            } else {
                privateViewMap.put(rb.Mix_Category__r.Name, new List<Recommended_Badge__c>{rb});
            }
        }

        return privateViewMap;
    }
}