force-app/main/default/objects/Mix_Category__c/Mix_Category__c.object-meta.xml
<CustomObject>
    <label>Mix Category</label>
    <nameField>
        <label>Mix Category</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mix Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Mix_Category__c/fields/Recommended_Badge_Mix__c.field-meta.xml
<CustomField>
    <fullName>Recommended_Badge_Mix__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Recommended Badge Mix</label>
    <referenceTo>Recommended_Badge_Mix__c</referenceTo>
    <relationshipLabel>Mix Categories</relationshipLabel>
    <relationshipName>Mix_Categories</relationshipName>
    <type>Lookup</type>
</CustomField>

DataModel/main/default/objects/Recommended_Badge__c/Recommended_Badge__c.object-meta.xml
<CustomObject>
    <label>Recommended Badge</label>
    <nameField>
        <displayFormat>RB-{0000000}</displayFormat>
        <label>Recommended Badge Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Recommended Badges</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Core/objects/Recommended_Badge__c/fields/Badge_Mix_Key__c.field-meta.xml
<CustomField>
    <fullName>Badge_Mix_Key__c</fullName>
    <label>Badge Mix Key</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Core/objects/Recommended_Badge__c/fields/BadgeAPIName__c.field-meta.xml
<CustomField>
    <fullName>BadgeAPIName__c</fullName>
    <label>Badge API Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Recommended_Badge__c/fields/Mix_Category__c.field-meta.xml
<CustomField>
    <fullName>Mix_Category__c</fullName>
    <label>Mix Category</label>
    <referenceTo>Mix_Category__c</referenceTo>
    <relationshipLabel>Recommended Badges</relationshipLabel>
    <relationshipName>Recommended_Badges</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Recommended_Badge__c/fields/Recommended_Badge_Mix__c.field-meta.xml
<CustomField>
    <fullName>Recommended_Badge_Mix__c</fullName>
    <label>Recommended Badge Mix</label>
    <referenceTo>Recommended_Badge_Mix__c</referenceTo>
    <relationshipLabel>Recommended Badges</relationshipLabel>
    <relationshipName>Recommended_Badges</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Recommended_Badge_Mix__c/Recommended_Badge_Mix__c.object-meta.xml
<CustomObject>
    <label>Recommended Badge Mix</label>
    <nameField>
        <label>Mix Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Recommended Badge Mixes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Triggers/classes/BadgeTrigger_Helper.cls
/**
 * @description       : A catchall trigger helper for RecommendedBadgeTrigger and RecommendedTrailTrigger.
 * @author            : Ben Learn
 * @group             : 
 * @last modified on  : 03-05-2023
 * @last modified by  : Ben Learn
**/
public without sharing class BadgeTrigger_Helper {
    /**
    * @description Method to populate unique key in the format [Badge Name]-[Recommended Badge Mix Name].
        Done to ensure that there aren't any duplicated recommended badges within the same recommended
        badge mix.
    * @author Ben Learn | 03-11-2022 
    * @param List<Recommended_Badge__c> newRecommendedBadges 
    * @param Map<Id, Recommended_Badge__c> oldRecommendedBadgeMap
    **/
    public static void populateBadgeMixKeys(List<Recommended_Badge__c> newRecommendedBadges, Map<Id, Recommended_Badge__c> oldRecommendedBadgeMap) {
        Set<Id> mixCategoryIds = new Set<Id>();

        for(Recommended_Badge__c newRecommendedBadge : newRecommendedBadges) {
            if(
                (newRecommendedBadge.Badge_Mix_Key__c == null) || 
                (oldRecommendedBadgeMap?.get(newRecommendedBadge.Id).Mix_Category__c != newRecommendedBadge.Mix_Category__c)
            ) {
                mixCategoryIds.add(newRecommendedBadge.Mix_Category__c);
            }
        }

        Map<Id, Mix_Category__c> mixCategoryMap = new Map<Id, Mix_Category__c>(new MixCategoriesSelector().selectByIdWithRecommendedBadgeMixNames(mixCategoryIds));
        for(Recommended_Badge__c newRecommendedBadge : newRecommendedBadges) {
            if(
                (newRecommendedBadge.Badge_Mix_Key__c == null) || 
                (oldRecommendedBadgeMap?.get(newRecommendedBadge.Id).Mix_Category__c != newRecommendedBadge.Mix_Category__c)
            ){
                String recommendedBadgeMixName = mixCategoryMap.get(newRecommendedBadge.Mix_Category__c).Recommended_Badge_Mix__r.Name;
                newRecommendedBadge.Badge_Mix_Key__c = newRecommendedBadge.BadgeAPIName__c + '-' + recommendedBadgeMixName; // change this
            }
        }
    }
}