force-app/main/default/objects/Mix_Category__c/Mix_Category__c.object-meta.xml
<CustomObject>
    <label>Mix Category</label>
    <nameField>
        <label>Mix Category</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mix Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Mix_Category__c/fields/Recommended_Badge_Mix__c.field-meta.xml
<CustomField>
    <fullName>Recommended_Badge_Mix__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Recommended Badge Mix</label>
    <referenceTo>Recommended_Badge_Mix__c</referenceTo>
    <relationshipLabel>Mix Categories</relationshipLabel>
    <relationshipName>Mix_Categories</relationshipName>
    <type>Lookup</type>
</CustomField>

DataModel/main/default/objects/Recommended_Badge__c/Recommended_Badge__c.object-meta.xml
<CustomObject>
    <label>Recommended Badge</label>
    <nameField>
        <displayFormat>RB-{0000000}</displayFormat>
        <label>Recommended Badge Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Recommended Badges</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Recommended_Badge__c/fields/Badge__c.field-meta.xml
<CustomField>
    <fullName>Badge__c</fullName>
    <label>Badge</label>
    <referenceTo>trailheadapp__Badge__c</referenceTo>
    <relationshipLabel>Recommended Badges</relationshipLabel>
    <relationshipName>Recommended_Badges</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Core/main/default/objects/Recommended_Badge__c/fields/Badge_Name__c.field-meta.xml
<CustomField>
    <fullName>Badge_Name__c</fullName>
    <formula>Badge__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Badge Name</label>
    <type>Text</type>
</CustomField>

DataModel/main/default/objects/Recommended_Badge__c/fields/High_Priority__c.field-meta.xml
<CustomField>
    <fullName>High_Priority__c</fullName>
    <defaultValue>false</defaultValue>
    <label>High Priority</label>
    <type>Checkbox</type>
</CustomField>

Core/objects/Recommended_Badge__c/fields/High_Priority_Id__c.field-meta.xml
<CustomField>
    <fullName>High_Priority_Id__c</fullName>
    <formula>IF(High_Priority__c, &apos;HP&apos; + Id, &apos;&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>High Priority Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Recommended_Badge__c/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <label>Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Level</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Recommended_Badge__c/fields/Mix_Category__c.field-meta.xml
<CustomField>
    <fullName>Mix_Category__c</fullName>
    <label>Mix Category</label>
    <referenceTo>Mix_Category__c</referenceTo>
    <relationshipLabel>Recommended Badges</relationshipLabel>
    <relationshipName>Recommended_Badges</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Recommended_Badge__c/fields/Recommended_Badge_Mix__c.field-meta.xml
<CustomField>
    <fullName>Recommended_Badge_Mix__c</fullName>
    <label>Recommended Badge Mix</label>
    <referenceTo>Recommended_Badge_Mix__c</referenceTo>
    <relationshipLabel>Recommended Badges</relationshipLabel>
    <relationshipName>Recommended_Badges</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Recommended_Badge__c/fields/Time_Estimate__c.field-meta.xml
<CustomField>
    <fullName>Time_Estimate__c</fullName>
    <formula>IF(TEXT(Hours_Estimate__c) != &apos;&apos;, TEXT(Hours_Estimate__c) &amp; &apos; hr &apos;, &apos;&apos;) &amp; 
IF(TEXT(Minutes_Estimate__c) != &apos;&apos;, TEXT(Minutes_Estimate__c) &amp; &apos; min&apos;, &apos;&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Time Estimate</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Recommended_Badge__c/fields/Time_Estimate_Minutes__c.field-meta.xml
<CustomField>
    <fullName>Time_Estimate_Minutes__c</fullName>
    <formula>Minutes_Estimate__c + Hours_Estimate__c * 60</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Time Estimate (Minutes)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Recommended_Badge__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Module</fullName>
                <default>true</default>
                <label>Module</label>
            </value>
            <value>
                <fullName>Project</fullName>
            </value>
            <value>
                <fullName>Superbadge</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Recommended_Badge__c/fields/URL__c.field-meta.xml
<CustomField>
    <fullName>URL__c</fullName>
    <formula>Badge__r.trailheadapp__URL__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>URL</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Recommended_Badge_Mix__c/Recommended_Badge_Mix__c.object-meta.xml
<CustomObject>
    <label>Recommended Badge Mix</label>
    <nameField>
        <label>Mix Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Recommended Badge Mixes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

DataModel/main/default/objects/Recommended_Badge_Mix__c/fields/Private_Mix__c.field-meta.xml
<CustomField>
    <fullName>Private_Mix__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Private Mix</label>
    <type>Checkbox</type>
</CustomField>

unpackageable/globalValueSets/Level.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Beginner</fullName>
        <default>true</default>
        <label>Beginner</label>
    </customValue>
    <customValue>
        <fullName>Intermediate</fullName>
    </customValue>
    <customValue>
        <fullName>Advanced</fullName>
    </customValue>
    <masterLabel>Level</masterLabel>
</GlobalValueSet>

PrivateMixView/main/default/classes/PrivateViewServiceTests.cls
/**
 * @description       : 
 * @author            : Ben Learn
 * @group             : 
 * @last modified on  : 12-22-2022
 * @last modified by  : Ben Learn
**/
@isTest
private class PrivateViewServiceTests {
    private static List<String> levels = new List<String>{
        'Beginner',
        'Intermediate',
        'Advanced'
    };

    private static List<String> types = new List<String>{
        'Module',
        'Project',
        'Superbadge'
    };

    private static String getRandomLevel() {
        return levels[Integer.valueOf(Math.floor(Math.random()*levels.size()))];
    }

    private static String getRandomType() {
        return types[Integer.valueOf(Math.floor(Math.random()*types.size()))];
    }

    @isTest
    private static void getMixCategoryData_test() {
        List<Recommended_Badge_Mix__c> testRecommendedBadgeMixes = new List<Recommended_Badge_Mix__c>();
        Boolean privateMix = false;
        for(Integer i = 0; i < 10; i++) {
            testRecommendedBadgeMixes.add(new Recommended_Badge_Mix__c(
                Name='Test Mix ' + i,
                Private_Mix__c=privateMix
            ));
            privateMix = !privateMix;
        }
        insert testRecommendedBadgeMixes;

        List<Mix_Category__c> testMixCategories = new List<Mix_Category__c>();
        for(Recommended_Badge_Mix__c rbm : testRecommendedBadgeMixes) {
            for(Integer i = 0; i < 4; i++) {
                testMixCategories.add(new Mix_Category__c(
                    Name=rbm.Name + ' Category ' + i,
                    Recommended_Badge_Mix__c=rbm.Id
                ));
            }
        }
        insert testMixCategories;

        testMixCategories = [
            SELECT Name, Recommended_Badge_Mix__r.Name, Recommended_Badge_Mix__r.Private_Mix__c
            FROM Mix_Category__c
            ORDER BY Name
        ];

        Test.startTest();
        List<Mix_Category__c> mixCategoryData = PrivateViewService.getMixCategoryData();
        Test.stopTest();

        System.assert(testMixCategories.equals(mixCategoryData), 'Expected Mix Category data to equal test data.');
    }

    @isTest
    private static void getPrivateMixRecommendedBadges_test() {
        List<trailheadapp__Badge__c> testBadges = new List<trailheadapp__Badge__c>();
        List<trailheadapp__Trail__c> testTrails = new List<trailheadapp__Trail__c>();

        for(Integer i = 0; i < 200; i++) {
            testBadges.add(new trailheadapp__Badge__c(
                Name='Test Badge ' + i,
                trailheadapp__Level__c=getRandomLevel(),
                trailheadapp__Type__c=getRandomType(),
                trailheadapp__API_Name__c='Test_Badge_' + i,
                trailheadapp__Description__c='Test Description',
                trailheadapp__Namespace__c='Test Namespace',
                trailheadapp__URL__c='www.test.com',
                trailheadapp__Icon__c='www.testicon.com'
            ));

            testTrails.add(new trailheadapp__Trail__c(
                Name='Test Trail ' + i,
                trailheadapp__Level__c=getRandomLevel(),
                trailheadapp__API_Name__c='Test_Trail_' + i,
                trailheadapp__Description__c='Test Description',
                trailheadapp__Namespace__c='Test Namespace',
                trailheadapp__URL__c='www.test.com',
                trailheadapp__Icon__c='www.testicon.com'
            ));
        }
        insert testBadges;
        insert testTrails;

        List<Recommended_Badge_Mix__c> testRecommendedBadgeMixes = new List<Recommended_Badge_Mix__c>{
            new Recommended_Badge_Mix__c(
                Name='Test Private Recommended Badge Mix',
                Private_Mix__c=true
            ),
            new Recommended_Badge_Mix__c(
                Name='Test Public Recommended Badge Mix'
            )
        };
        insert testRecommendedBadgeMixes;

        List<Mix_Category__c> testMixCategories = new List<Mix_Category__c>();
        for(Integer i = 0; i < 20; i++) {
            testMixCategories.add(new Mix_Category__c(
                Name='Test Mix Category ' + i,
                Recommended_Badge_Mix__c=testRecommendedBadgeMixes[Math.mod(i, 2)].Id
            ));
        }
        insert testMixCategories;

        List<Recommended_Badge__c> testRecommendedBadges = new List<Recommended_Badge__c>();
        for(Integer i = 0; i < 200; i++) {
            if(Math.mod(i, 10) == 0) {
                testRecommendedBadges.add(new Recommended_Badge__c(
                    Mix_Category__c=testMixCategories[Integer.valueOf(Math.floor(i/10))].Id,
                    Badge__c=testBadges[i].Id,
                    High_Priority__c=true
                ));
            } else {
                testRecommendedBadges.add(new Recommended_Badge__c(
                    Mix_Category__c=testMixCategories[Integer.valueOf(Math.floor(i/10))].Id,
                    Badge__c=testBadges[i].Id
                ));
            }
        }
        insert testRecommendedBadges;

        List<Recommended_Badge__c> resultRecommendedBadges = [
            SELECT Badge_Name__c, High_Priority__c, High_Priority_Id__c, Level__c, Time_Estimate_Minutes__c, Time_Estimate__c, Type__c, URL__c, Mix_Category__r.Name 
            FROM Recommended_Badge__c 
            WHERE Mix_Category__r.Recommended_Badge_Mix__r.Private_Mix__c = true ORDER BY Badge_Name__c
        ];

        Map<String, List<Recommended_Badge__c>> resultRecommendedBadgeMap = new Map<String, List<Recommended_Badge__c>>();
        resultRecommendedBadgeMap.put('High Priority', new List<Recommended_Badge__c>());
        for(Recommended_Badge__c rb : resultRecommendedBadges) {
            if(rb.High_Priority__c) {
                List<Recommended_Badge__c> currentRecommendedBadges = resultRecommendedBadgeMap.get('High Priority');
                currentRecommendedBadges.add(rb);
                resultRecommendedBadgeMap.put('High Priority', currentRecommendedBadges);
            }

            if(resultRecommendedBadgeMap.get(rb.Mix_Category__r.Name) != null) {
                List<Recommended_Badge__c> currentRecommendedBadges = resultRecommendedBadgeMap.get(rb.Mix_Category__r.Name);
                currentRecommendedBadges.add(rb);
                resultRecommendedBadgeMap.put(rb.Mix_Category__r.Name, currentRecommendedBadges);
            } else {
                resultRecommendedBadgeMap.put(rb.Mix_Category__r.Name, new List<Recommended_Badge__c>{rb});
            }
        }

        Test.startTest();
        Map<String, List<Recommended_Badge__c>> privateViewMap = PrivateViewService.getPrivateMixRecommendedBadges();
        Test.stopTest();

        System.assert(resultRecommendedBadgeMap.equals(privateViewMap), 'Expected private view Recommended Badges to equal test data.');
    }
}