Core/main/default/objects/Recommended_Trail__c/Recommended_Trail__c.object-meta.xml
<CustomObject>
    <label>Recommended Trail</label>
    <nameField>
        <displayFormat>RT-{0000000}</displayFormat>
        <label>Recommended Trail Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Recommended Trails</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Core/objects/Recommended_Trail__c/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <description>Value of the trailheadapp__Level__c field on corresponding trailheadapp__Trail__c.</description>
    <label>Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Level</valueSetName>
    </valueSet>
</CustomField>

Core/objects/Recommended_Trail__c/fields/TrailAPIName__c.field-meta.xml
<CustomField>
    <fullName>TrailAPIName__c</fullName>
    <description>Value of the trailheadapp__API_Name__c field on the corresponding trailheadapp__Trail__c record.</description>
    <label>Trail API Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

Core/globalValueSets/Level.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Beginner</fullName>
        <default>true</default>
        <label>Beginner</label>
    </customValue>
    <customValue>
        <fullName>Intermediate</fullName>
    </customValue>
    <customValue>
        <fullName>Advanced</fullName>
    </customValue>
    <customValue>
        <fullName>Superbadge Unit</fullName>
    </customValue>
    <customValue>
        <fullName>Superbadge</fullName>
    </customValue>
    <customValue>
        <fullName>Super Set</fullName>
    </customValue>
    <masterLabel>Level</masterLabel>
</GlobalValueSet>

Core/classes/selectors/RecommendedTrailsSelector.cls
/**
 * Selector class for Recommended Trail custom object.
 * @author Ben Learn
 * @since 01-29-2023
 * @group Core
 */
public inherited sharing class RecommendedTrailsSelector extends ApplicationSelector {
    /**
     * fflib method to hold the fields to always be queried by the selector
     * @return  `List<Schema.SObjectField>`
     */
    public List<Schema.SObjectField> getSObjectFieldList() {
        return new List<Schema.SObjectField> {
            Recommended_Trail__c.Id,
            Recommended_Trail__c.Level__c
        };
    }

    /**
     * fflib method to return the sObjectType of the object being queried
     * @return  `Schema.SObjectType`
     */    
    public Schema.SObjectType getSObjectType() {
        return Recommended_Trail__c.sObjectType;
    }

    /**
     * default constructor
     */    
    public RecommendedTrailsSelector() {
        super();
    }

    /**
     * constructor to call fflib_SObjectSelector constructor with/without field set fields included and using specified DataAccess
     * @param includeFieldSetFields 
     * @param dataAccess 
     */
    public RecommendedTrailsSelector(Boolean includeFieldSetFields, fflib_SObjectSelector.DataAccess dataAccess) {
        super(includeFieldSetFields, dataAccess);
    }

    /**
     * Returns all Recommended_Trail__c records that have a matching TrailAPIName__c, including fields in the Core field set
     * @param trailAPINames 
     * @return  `List<Recommended_Trail__c>`
     */
    public List<Recommended_Trail__c> selectTrailsByAPINames(Set<String> trailAPINames) {
        return (List<Recommended_Trail__c>) Database.query(
            newQueryFactory().selectFieldSet(Schema.SObjectType.Recommended_Trail__c.fieldSets.Core, false).
            setCondition('TrailAPIName__c IN :trailAPINames').
            toSOQL()
        );
    }

    /**
     * Returns the API name of the Recommended_Trail__c with the provided Id by including fields from the Triggers field set
     * @param recommendedTrailId 
     * @return  `Recommended_Trail__c`
     */
    public Recommended_Trail__c selectTrailAPINameById(Id recommendedTrailId) {
        return (Recommended_Trail__c) Database.query(
            newQueryFactory().selectFieldSet(Schema.SObjectType.Recommended_Trail__c.fieldSets.Triggers, false).
            setCondition('Id = \'' + recommendedTrailId + '\'').
            toSOQL()
        )[0];
    }
}