SortCustomMetadata/main/default/objects/Sort_Option__mdt/Sort_Option__mdt.object-meta.xml
<CustomObject>
    <label>Sort Option</label>
    <pluralLabel>Sort Options</pluralLabel>
</CustomObject>

SortCustomMetadata/main/default/objects/Sort_Option__mdt/fields/Sortable_LWC__c.field-meta.xml
<CustomField>
    <fullName>Sortable_LWC__c</fullName>
    <label>Sortable LWC</label>
    <referenceTo>Sortable_LWC__mdt</referenceTo>
    <relationshipLabel>Sort Options</relationshipLabel>
    <relationshipName>Sort_Options</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

SortCustomMetadata/main/default/objects/Sortable_LWC__mdt/Sortable_LWC__mdt.object-meta.xml
<CustomObject>
    <label>Sortable LWC</label>
    <pluralLabel>Sortable LWCs</pluralLabel>
</CustomObject>

SortCustomMetadata/main/default/classes/SortCustomMetadataService.cls
/**
 * @description       : 
 * @author            : Ben Learn
 * @group             : 
 * @last modified on  : 03-13-2022
 * @last modified by  : Ben Learn
**/
public without sharing class SortCustomMetadataService {
    @AuraEnabled(cacheable=true)
    public static List<Sort_Option__mdt> getSortOptions(String componentName) {
        return [SELECT MasterLabel, Field_API_Name__c FROM Sort_Option__mdt WHERE Sortable_LWC__r.MasterLabel = :componentName];
    }
}