Triggers/objects/TrailheadEntityURLMapping__mdt/TrailheadEntityURLMapping__mdt.object-meta.xml
<CustomObject>
    <description>Custom metadata type to hold URL mappings for Badges, Projects, Superbadges, and Trails from the default https://developer.salesforce.com domain to the https://trailhead.salesforce.com domain.</description>
    <label>Trailhead Entity URL Mapping</label>
    <pluralLabel>Trailhead Entity URL Mappings</pluralLabel>
</CustomObject>

Triggers/objects/TrailheadEntityURLMapping__mdt/fields/DefaultPath__c.field-meta.xml
<CustomField>
    <fullName>DefaultPath__c</fullName>
    <description>Default path stored in the trailheadapp__URL__c field on the trailheadapp__Badge__c/trailheadapp__Trail__c record.</description>
    <label>Default Path</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

Triggers/objects/TrailheadEntityURLMapping__mdt/fields/TrailheadEntityType__c.field-meta.xml
<CustomField>
    <fullName>TrailheadEntityType__c</fullName>
    <description>Type of Trailhead Entity for URL mapping.</description>
    <label>Trailhead Entity Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Module</fullName>
                <default>true</default>
                <label>Module</label>
            </value>
            <value>
                <fullName>Project</fullName>
            </value>
            <value>
                <fullName>Superbadge</fullName>
            </value>
            <value>
                <fullName>Trail</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Triggers/objects/TrailheadEntityURLMapping__mdt/fields/TrailheadPath__c.field-meta.xml
<CustomField>
    <fullName>TrailheadPath__c</fullName>
    <description>Mapped Trailhead path for Trailhead Entity Type.</description>
    <label>Trailhead Path</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

Triggers/classes/tests/TrailheadEntityURLMappingsSelector_Tests.cls
@isTest(IsParallel=true)
private class TrailheadEntityURLMappingsSelector_Tests {
    @isTest
    private static void getSObjectFieldList_test() {
        List<Schema.SObjectField> expectedFieldList = new List<Schema.SObjectField> {
            TrailheadEntityURLMapping__mdt.DefaultPath__c,
            TrailheadEntityURLMapping__mdt.TrailheadEntityType__c,
            TrailheadEntityURLMapping__mdt.TrailheadPath__c
        };

        Assert.areEqual(expectedFieldList, new TrailheadEntityURLMappingsSelector().getSObjectFieldList(), SelectorTestErrorMessages.SOBJECT_FIELD_LIST_ERROR_MESSAGE);
    }

    @isTest
    private static void getSObjectType_test() {
        Assert.areEqual(TrailheadEntityURLMapping__mdt.sObjectType, new TrailheadEntityURLMappingsSelector().getSObjectType(), SelectorTestErrorMessages.SOBJECT_TYPE_ERROR_MESSAGE);
    }

    @isTest
    private static void selectAll_test() {
        Map<Id, TrailheadEntityURLMapping__mdt> expectedURLMappingsById = new Map<Id, TrailheadEntityURLMapping__mdt>([SELECT Id FROM TrailheadEntityURLMapping__mdt]);
        Map<Id, TrailheadEntityURLMapping__mdt> resultURLMappingsById = new Map<Id, TrailheadEntityURLMapping__mdt>(new TrailheadEntityURLMappingsSelector().selectAll());

        Assert.areEqual(expectedURLMappingsById.keySet(), resultURLMappingsById.keySet(), 'Expected all TrailheadEntityURLMapping records to be returned.');
    }
}