Triggers/objects/TrailheadEntityURLMapping__mdt/TrailheadEntityURLMapping__mdt.object-meta.xml
<CustomObject>
    <description>Custom metadata type to hold URL mappings for Badges, Projects, Superbadges, and Trails from the default https://developer.salesforce.com domain to the https://trailhead.salesforce.com domain.</description>
    <label>Trailhead Entity URL Mapping</label>
    <pluralLabel>Trailhead Entity URL Mappings</pluralLabel>
</CustomObject>

Triggers/objects/TrailheadEntityURLMapping__mdt/fields/DefaultPath__c.field-meta.xml
<CustomField>
    <fullName>DefaultPath__c</fullName>
    <description>Default path stored in the trailheadapp__URL__c field on the trailheadapp__Badge__c/trailheadapp__Trail__c record.</description>
    <label>Default Path</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

Triggers/objects/TrailheadEntityURLMapping__mdt/fields/TrailheadEntityType__c.field-meta.xml
<CustomField>
    <fullName>TrailheadEntityType__c</fullName>
    <description>Type of Trailhead Entity for URL mapping.</description>
    <label>Trailhead Entity Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Module</fullName>
                <default>true</default>
                <label>Module</label>
            </value>
            <value>
                <fullName>Project</fullName>
            </value>
            <value>
                <fullName>Superbadge</fullName>
            </value>
            <value>
                <fullName>Trail</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Triggers/objects/TrailheadEntityURLMapping__mdt/fields/TrailheadPath__c.field-meta.xml
<CustomField>
    <fullName>TrailheadPath__c</fullName>
    <description>Mapped Trailhead path for Trailhead Entity Type.</description>
    <label>Trailhead Path</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

Triggers/classes/selectors/TrailheadEntityURLMappingsSelector.cls
/**
 * Selector class for Trailhead Entity URL Mapping custom metadata type.
 * @author Ben Learn
 * @since 07-15-2024
 * @group Core
 */
public inherited sharing class TrailheadEntityURLMappingsSelector extends ApplicationSelector {
    /**
     * fflib method to hold the fields to always be queried by the selector
     * @return  `List<Schema.SObjectField>`
     */
    public List<Schema.SObjectField> getSObjectFieldList() {
        return new List<Schema.SObjectField>{
            TrailheadEntityURLMapping__mdt.DefaultPath__c,
            TrailheadEntityURLMapping__mdt.TrailheadEntityType__c,
            TrailheadEntityURLMapping__mdt.TrailheadPath__c
        };
    }

    /**
     * fflib method to return the sObjectType of the object being queried
     * @return  `Schema.SObjectType`
     */    
    public Schema.SObjectType getSObjectType() {
        return TrailheadEntityURLMapping__mdt.sObjectType;
    }

    /**
     * returns all TrailheadEntityURLMapping__mdt records
     * @return  `List<TrailheadEntityURLMapping__mdt>`
     */    
    public List<TrailheadEntityURLMapping__mdt> selectAll() {
        return (List<TrailheadEntityURLMapping__mdt>) Database.query(newQueryFactory().toSOQL());
    }
}