Core/objects/RecommendedArticle__c/RecommendedArticle__c.object-meta.xml
<CustomObject>
    <description>A recommended programming blog article or other resource.</description>
    <label>Recommended Article</label>
    <nameField>
        <displayFormat>RA-{0000000}</displayFormat>
        <label>Recommended Article Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Recommended Articles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Core/objects/RecommendedArticle__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <description>Title of the article or other resource.</description>
    <label>Title</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

Core/objects/RecommendedArticle__c/fields/URL__c.field-meta.xml
<CustomField>
    <fullName>URL__c</fullName>
    <description>The URL for the article or other resource.</description>
    <label>URL</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

RecommendedArticles/classes/RecommendedArticlesController.cls
/**
 * Apex controller for recommendedArticlesContainer component
 * @author Ben Learn
 * @since 08-05-2024
 */
public with sharing class RecommendedArticlesController {
    @AuraEnabled(cacheable=true)
    public static List<RecommendedArticle__c> getRecommendedArticles() {
        List<RecommendedArticle__c> articles = [SELECT Id, Name, Title__c, URL__c, (SELECT Id, Topic.Name FROM TopicAssignments) FROM RecommendedArticle__c];
        return articles;
    }

    @AuraEnabled(cacheable=true)
    public static List<Topic> getTopics() {
        return [SELECT Name FROM Topic WHERE Id IN (SELECT TopicId FROM TopicAssignment WHERE EntityType = 'RecommendedArticle__c') ORDER BY Name];
    }
}