Core/objects/RecommendedArticle__c/RecommendedArticle__c.object-meta.xml
<CustomObject>
    <description>A recommended programming blog article or other resource.</description>
    <label>Recommended Article</label>
    <nameField>
        <displayFormat>RA-{0000000}</displayFormat>
        <label>Recommended Article Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Recommended Articles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Core/objects/RecommendedArticle__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <description>Title of the article or other resource.</description>
    <label>Title</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

Core/objects/RecommendedArticle__c/fields/URL__c.field-meta.xml
<CustomField>
    <fullName>URL__c</fullName>
    <description>The URL for the article or other resource.</description>
    <label>URL</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

Core/classes/testsupport/RecommendedArticleTS.cls
@isTest
public class RecommendedArticleTS extends TestSupport.DataGeneration {
    /**
     * No arg constructor
     */    
    public RecommendedArticleTS() {
        this(new Map<String, Object>(), new List<TestSupport.TestDataField>());
    }

    /**
     * Constructor with configuration options
     * @param options 
     */    
    public RecommendedArticleTS(Map<String, Object> options) {
        this(options, new List<TestSupport.TestDataField>());
    }

    /**
     * Constructor with custom field specs
     * @param fieldSpecs 
     */    
    public RecommendedArticleTS(List<TestSupport.TestDataField> fieldSpecs) {
        this(new Map<String, Object>(), fieldSpecs);
    }

    /**
     * Constructor with configuration options and custom field specs
     * @param options 
     * @param fieldSpecs 
     */    
    public RecommendedArticleTS(Map<String, Object> options, List<TestSupport.TestDataField> fieldSpecs) {
        super(options, fieldSpecs);
        this.SOBJECT_TYPE = 'RecommendedArticle__c';
    }

    protected override Map<Schema.SObjectField, TestSupport.TestDataField> loadDefaultSpecsByField() {
        return new Map<Schema.SObjectField, TestSupport.TestDataField>{
            RecommendedArticle__c.Title__c => new CounterSuffixField(RecommendedArticle__c.Title__c, 'Test Title '),
            Recommendedarticle__c.URL__c => new TestSupport.TestDataField(RecommendedArticle__c.URL__c, 'www.test.com')
        };
    }
}