SortCustomMetadata/main/default/objects/Sortable_Field__mdt/Sortable_Field__mdt.object-meta.xml
<CustomObject>
    <label>Sortable Field</label>
    <pluralLabel>Sortable Fields</pluralLabel>
</CustomObject>

SortCustomMetadata/objects/Sortable_Field__mdt/fields/Sortable_LWC__c.field-meta.xml
<CustomField>
    <fullName>Sortable_LWC__c</fullName>
    <label>Sortable LWC</label>
    <referenceTo>Sortable_LWC__mdt</referenceTo>
    <relationshipName>Sort_Options</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

SortCustomMetadata/main/default/objects/Sortable_Field_Value__mdt/Sortable_Field_Value__mdt.object-meta.xml
<CustomObject>
    <label>Sortable Field Value</label>
    <pluralLabel>Sortable Field Values</pluralLabel>
</CustomObject>

SortCustomMetadata/objects/Sortable_Field_Value__mdt/fields/Sortable_Field__c.field-meta.xml
<CustomField>
    <fullName>Sortable_Field__c</fullName>
    <label>Sortable Field</label>
    <referenceTo>Sortable_Field__mdt</referenceTo>
    <relationshipLabel>Sortable Field Values</relationshipLabel>
    <relationshipName>Sortable_Field_Values</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

SortCustomMetadata/main/default/objects/Sortable_LWC__mdt/Sortable_LWC__mdt.object-meta.xml
<CustomObject>
    <label>Sortable LWC</label>
    <pluralLabel>Sortable LWCs</pluralLabel>
</CustomObject>

SortCustomMetadata/classes/SortCustomMetadataControllerTests.cls
/**
 * @description       : Test class for SortCustomMetadataController.
 * @author            : Ben Learn
 * @last modified on  : 01-09-2023
 * @last modified by  : Ben Learn
**/
@isTest
private class SortCustomMetadataControllerTests {
    @isTest
    private static void getSortOptions_test() {
        List<Sortable_Field__mdt> sortableFields = [
            SELECT MasterLabel, Field_API_Name__c, Sortable_LWC__r.MasterLabel,
            (SELECT MasterLabel, Sort_Order__c FROM Sortable_Field_Values__r)
            FROM Sortable_Field__mdt
        ];

        String testComponentName;
        if(sortableFields.size() == 0) {
            testComponentName = 'test';
        } else {
            testComponentName = sortableFields[0].Sortable_LWC__r.MasterLabel;
            for(Sortable_Field__mdt sortableField : sortableFields) {
                if(sortableField.Sortable_LWC__r.MasterLabel != testComponentName) {
                    sortableFields.remove(sortableFields.indexOf(sortableField));
                }
            }
        }

        Test.startTest();
        List<Sortable_Field__mdt> sortOptions = SortCustomMetadataController.getSortOptions(testComponentName);
        Test.stopTest();

        Map<Id, Sortable_Field__mdt> sortableFieldMap = new Map<Id, Sortable_Field__mdt>(sortableFields);
        for(Sortable_Field__mdt sortOption : sortOptions) {
            System.assert(sortableFieldMap.containsKey(sortOption.Id), 'Expected sort options to be the same.');
        }
    }
}